### ISSUE TITLE
Site not loading

### ISSUE THREAD

**Issue by g0dzcsgo** [vilhelmprytz/pterodactyl-installer#104]
Installed python etc, then i ran the script wrote all the info right then it said "Your site should work now" and then i went to the URL but.... its just infinetely loading and then it says:
This page isn’t working VPS IP didn’t send any data.
ERR_EMPTY_RESPONSE

I am using google cloud server, tried installing this software several times, with this script and also without it but its the same result.... Please help

**Comment by Linux123123** [comment]
For support go to our discord. We will surely help. This is most likely not a problem with the script.

**Comment by vilhelmprytz** [comment]
> Installed python etc, then i ran the script wrote all the info right then it said "Your site should work now" and then i went to the URL but.... its just infinetely loading and then it says:
> This page isn’t working VPS IP didn’t send any data.
> ERR_EMPTY_RESPONSE
> 
> I am using google cloud server, tried installing this software several times, with this script and also without it but its the same result.... Please help

As @Linux123123, this is not likely related to the script. Refer to Discord for support. Closing.
