### ISSUE TITLE
Wings: MySQL isn't needed

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#105]
The daemon installation doesn't strictly need to have `mysql` installed.

Yes, I know that having a database would make it possible for servers to use it, but as far as I know you would need to **open port 3306**, make it **bind to ip 0.0.0.0**, **create database user** to have a functioning pterodactyl database host, because databases are created from panel install. In most cases having the panel database and exposing it to other `wings` instances is a better solution if the `wings` isn't local to panel install.

Also you always say stick to [pterodactyl instructions](https://pterodactyl.io/panel/1.0/getting_started.html), in which there is no mention of `mysql` in daemon section.

**Comment by vilhelmprytz** [comment]
The option to install MariaDB via the Wings script was suggested quite a while back, see #47 and #23 for reference. Are you suggesting we either 1) remove the option completely or 2) make it more useful, e.g. create a MySQL user and set up the port/IP settings correctly automatically?

**Comment by Linux123123** [comment]
I think 1, but not removing, but moving to the asking to the end. Also it could be a separate script maybe and then it could also configure it. I don't like adding more code to wings because it will become hard to maintain.

**Comment by vilhelmprytz** [comment]
> I think 1, but not removing, but moving to the asking to the end. Also it could be a separate script maybe and then it could also configure it. I don't like adding more code to wings because it will become hard to maintain.

Ah, I see your point. I reckon it's enough to move it to the end. But perhaps a separate script. Do you mean that the separate script would be accessible from the master install script? If you want to talk about hard to maintain, I'd say the panel script is definitely worse... :sunglasses:

**Comment by Linux123123** [comment]
I think if my PR mergers it won't be that bad.

I didn't really finalize my thought in the last comment. I meant that we would have a separate script (`install-mysql.sh`) and we could call it at the end if user chose so. It would install mysql and configure it.

**Comment by vilhelmprytz** [comment]
Ah, yes, that would work too. Although maybe a bit excessive? We can review the situation after your two PRs have merged and perform a new evaluation depending on what we think is suitable then?

**Comment by Linux123123** [comment]
Yes, I think this plan would be great.

**Comment by vilhelmprytz** [comment]
Should we review this again? [Isn't doing this](https://github.com/vilhelmprytz/pterodactyl-installer/issues/105#issuecomment-721930208) pretty much the same as it is?

**Comment by vilhelmprytz** [comment]
#220 is duplicate, but we've decided to implement the suggestion. Closing. As always, thank you for submitting the issue @Linux123123
