### ISSUE TITLE
Panel: SElinux unsupported on some providers

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#106]
**Describe the bug**
The script won't run past the SElinux part, because it fails at that point.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the script on CentOS 7 or 8
4. Come to the part where SElinux is enabled and get an error

**Expected behaviour**
The script should skip the SElinux part when it is unsupported.

**OS (please complete the following information):**
 - OS: CentOS 7 and 8
 - Installation: panel

**Additional context**
This isn't a crucial install step, so it could be fixed with ` || true` or by checking if SElinux is supported by the kernel.

**Comment by vilhelmprytz** [comment]
Are you able to provide some more context about this issue? CentOS 7 and 8 used to work without this issue. Is SELinux not supported on all machines?

**Comment by Linux123123** [comment]
There are some hosts that use custom kernels that have SELinux disabled. For example OVH.

**Comment by vilhelmprytz** [comment]
> There are some hosts that use custom kernels that have SELinux disabled. For example OVH.

Oh, I see. I'll implement your suggested fix right away, I reckon that's sufficient! Thanks for reporting the issue! :+1:
