### ISSUE TITLE
CentOS 7 support (panel)

### ISSUE THREAD

**Issue by OsweRRR** [VilhelmPrytz/pterodactyl-installer#11]
You can add support for 7 centos to install the panel, I really appreciate your work.

**Comment by VilhelmPrytz** [comment]
Thank you for your interest. I'll work on it when I have the time. Feel free to send a pull request with any suggested changes.

**Comment by VilhelmPrytz** [comment]
I have finally started working on this issue. Hopefully support will be available for both CentOS 7 and 8 in the near future!

**Comment by VilhelmPrytz** [comment]
CentOS 7 and 8 is now supported for panel and daemon!
