### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by Nitroc1701** [vilhelmprytz/pterodactyl-installer#126]
Hi, when i do the command bash <(curl -s https://pterodactyl-installer.se) as a root
It says Host is down
What does it mean ?

**Comment by Nitroc1701** [comment]
I want an answer please

**Comment by vilhelmprytz** [comment]
Please verify that your network connectivity is working (to other hosts). There should be no problems with our host. Reopen the issue if this is not the case. Closing.
