### ISSUE TITLE
wings: Allow user to enter auto-deploy command

### ISSUE THREAD

**Issue by JustinPooters** [vilhelmprytz/pterodactyl-installer#129]
**Describe the solution you'd like**
I'd like to use the auto-deploy option in pterodactyl to setup the daemon config automatic with just 1 user input command.

**Describe alternatives you've considered**
This is also visible in the Revenact script (that doesn't work 9/10 times)

**Comment by vilhelmprytz** [comment]
Thanks for the feature request! As I've come to understand it, you could just copy the command displayed from the Pterodactyl panel interface to your terminal. I first understood your feature request as something else. Is it the process of pasting the command that you want the script to ease the process or is it something else?

**Comment by JustinPooters** [comment]
Its the Auto-Deploy function, where you can only paste the command and it does the "auto setup".

**Comment by Linux123123** [comment]
You don't need any special things. When you complete the wings install, you create a node. In node configuration you click generate token. You get the command you copy it and you paste it to the console. That is it.

**Comment by vilhelmprytz** [comment]
The other script you are referring to simply executes the command the user inputs. I guess we could do something like this but I am not too sure what upside it has? https://github.com/Revenact/Pterodactyl-Script/blob/d4bf4ea86776d1338e43af0d976804b40daafd50/install.sh#L1545

**Comment by Linux123123** [comment]
I think this is not needed. Why don't just paste the command straight to console after the installation is done, if you already have it copied?

**Comment by vilhelmprytz** [comment]
I think we could do something like this since I can see a bit why it's useful. While the "auto-deploy" command itself could just be pasted into your terminal, it's about when this command is being run and the fact that Wings is started right afterwards. It all means a smoother experience, I guess. I'll see if I can implement something like this at the end.
