### ISSUE TITLE
The Ubuntu Certbot Repository does not have a Release file.

### ISSUE THREAD

**Issue by TheBossTim** [vilhelmprytz/pterodactyl-installer#130]
**Describe the bug**
Installing both the panel and wings on Ubuntu 20.04.1 LTS fails due to the certbot repository not having a release file.
[Paste here](https://pastebin.com/9hXkNst2)

**To Reproduce**
Steps to reproduce the behaviour:
1. Use a fresh install of Ubuntu 20.04.1 LTS
2. Run `bash <(curl -s https://pterodactyl-installer.se)`
3. Choose option 3
4. Fill in basic details and configure firewall = Y, Auto config HTTPS = Y
5. Observe

**Expected behaviour**
The installer should run without issues

**Screenshots**

**OS (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Installation: Both

**Additional context**
After looking the issue up, it seems that `--allow-unauthenticated` needs to be append to the apt command, although through testing I haven't been able to get it to work

**Comment by vilhelmprytz** [comment]
Are you using the `0.7.x` version of the script (legacy, not supported) or the latest, `v1.x`, version of the script?

**Comment by TheBossTim** [comment]
> Are you using the `0.7.x` version of the script (legacy, not supported) or the latest, `v1.x`, version of the script?

Since I used `bash <(curl -s https://pterodactyl-installer.se)` and chose option 3, then I assume the latest as there is also option 6 which does the same thing but with older versions of both the panel and wings.

**Comment by Linux123123** [comment]
Are you sure you are on a clean OS? It seems like you have tried installing pterodactyl on your own and then tried to run the script. We don't add `certbot` repository via ppa, we use `certbot` provided from the main repos.

**Comment by vilhelmprytz** [comment]
I understand. Option 3 would be the latest version. I've read your included Pastebin and it seems to me that you've added the certbot PPA. This script does not add the certbot PPA and instead uses the version of certbot already included in the repository of Ubuntu.

**Comment by TheBossTim** [comment]
> don't add `certbot` repository via ppa, we use `certbot` provided from the main repos.

Odd. It could be that my OS was installed and packaged with some addons as this is my first time installing in a VM. I'll double check and reinstall, then see if anything changes.

**Comment by TheBossTim** [comment]
A reinstall seems to have fixed it. Apologies for the invalid bug report

**Comment by vilhelmprytz** [comment]
@TheBossTim May I ask what hosting provider you are using?
