### ISSUE TITLE
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-panel' at line 1

### ISSUE THREAD

**Issue by RuneGaming** [vilhelmprytz/pterodactyl-installer#138]
**Describe the bug**
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-panel' at line 1
**To Reproduce**
Steps to reproduce the behaviour:
i just tried to install it

**Expected behaviour**
it installs 
**Console before error**
* Downloaded pterodactyl panel files & installed composer dependencies!
* Performing MySQL queries..
* Creating MySQL user..
* Creating database..
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-panel' at line 1
root@smpeen:~/pterodactyl-installer#

**OS (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation: panel

**Comment by vilhelmprytz** [comment]
What database credentials were you using? MariaDB doesn’t like the hyphen, `-`, you used in the database name. I’d recommend sticking to the default values where possible.

Closing. Reopen if this is a issue with the script.
