### ISSUE TITLE
Unsupported version of Ubuntu

### ISSUE THREAD

**Issue by PotatoLordGrif** [VilhelmPrytz/pterodactyl-installer#14]
**Describe the bug**
Using the install script provided, it completes the first configuration step, then sends the error "Unsupported version of Ubuntu"
**To Reproduce**
Steps to reproduce the behaviour:
1. Run script
2. Complete Initial Configuration
3. Answer yes to continue installation

**Expected behaviour**
Expected behavior is for the installation to continue and finish.. not give an error

**OS (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation: panel

**Additional context**
this is after a fresh install, only updating and installing curl onto the server.

**Comment by VilhelmPrytz** [comment]
Thank you for your report. This issue has been solved as of https://github.com/VilhelmPrytz/pterodactyl-installer/commit/2c91a22fff2a92bf9f5544573f83a7cfea92567b Issue was caused by changes in https://github.com/VilhelmPrytz/pterodactyl-installer/issues/13
