### ISSUE TITLE
A way to easily uninstall Pterodactyl and Wings

### ISSUE THREAD

**Issue by BreadcrumbIsTaken** [vilhelmprytz/pterodactyl-installer#141]
**Is your feature request related to a problem? Please describe.**
I sometimes need to uninstall pterodactyl but i do not know what files to uninstall because I use this installer. 

**Describe the solution you'd like**
I think that a good solution for this is to have the option to uninstall all the pterodactyl and wings files using the pterodactyl installer.

**Describe alternatives you've considered**
I have considered wiping the machine, but that can get very tedious.

**Comment by vilhelmprytz** [comment]
@Linux123123 has a PR, #123. It's in progress.
