### ISSUE TITLE
Buster: ufw: command not found

### ISSUE THREAD

**Issue by originalodz** [vilhelmprytz/pterodactyl-installer#146]
I'm running latest version of Buster and during the ufw configuration in the script, as root, I get this error:

/dev/fd/62: line 655: ufw: command not found

What I've tried:
- Run without ufw preinstalled.
- Run with ufw preinstalled.

It's a minimal server with nothing else on it. Any suggestions would be deeply appreciated. I've read about that it could be that I'm missing /usr/bin in PATH but that's not the case.. and I can't really see that it should be the issue.

**Comment by vilhelmprytz** [comment]
Can you check whether ufw was installed or not (so we know it’s not because it’s not in PATH)? Also, can you provide more log information?

**Comment by originalodz** [comment]
Unfortunately I'm a bit novice, could you point me in the right direction of how to get you log info unless below is sufficient?

[https://pastebin.com/rAyN0r17](https://pastebin.com/rAyN0r17)

**Comment by vilhelmprytz** [comment]
That should be enough and it looks to me like `ufw` was installed correctly which is extremely strange. Can you try `command -v ufw`?

**Comment by originalodz** [comment]
**command -v ufw** gives me no ouput at all no matter if I run it as root or sudo user. General ufw commands work as sudo user but not as root, ex **sudo ufw status**. This is while having ufw not preinstalled and by running your script, getting the error above and then trying command -v and ufw status.

I assume you're trying to check ufw version either if there's any response or what actual version gets installed so I ran **sudo ufw version**: 0.36 but that does not work as root (_bash: ufw: command not found_)

**Comment by vilhelmprytz** [comment]
`command -v ufw` is supposed to be empty if the command `ufw` is not in PATH, the version of ufw is irrelevant. Can you log in as a non-root user where you've been able to use ufw and do `sudo echo $PATH`? After that, log in as root and run `echo $PATH`. Can you include the outputs of these two commands here?

**Comment by originalodz** [comment]
Sudo user PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
Root PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

Hm. Could this have anything to do with that I'm using su and have root login disabled?

**Comment by vilhelmprytz** [comment]
So `ufw` is in `/usr/sbin` which is in neither of yours. Did you not say that `ufw` worked when using `sudo ufw` but not when logged in as root and running `ufw`?

**Comment by vilhelmprytz** [comment]
Looks to me like it's a problem with Debian. See [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918754#20). Try `su -` and not `su root`.

**Comment by originalodz** [comment]
> 
> 
> So `ufw` is in `/usr/sbin` which is in neither of yours. Did you not say that `ufw` worked when using `sudo ufw` but not when logged in as root and running `ufw`?

That is correct. Regarding using `su -` it got past that problem now. Currently running the rest of the installation, will report back here or close post when done.

**Comment by originalodz** [comment]
Another issue popped up in regards to letsencrypt (Connection refused) but using `su -` instead of `su` or `su root` worked out for the issue in this topic. As the issue with letsencrypt is not relevant to this post, would you prefer;

* That I create a new post
* Ask about it in this post
* Come back after looking at other resources

In some sense it could be relevant to the script itself, could also be an issue from my side. (only using ufw configured entirely by the script, no firewall (hard/soft) between server and isp currently)

**Comment by vilhelmprytz** [comment]
I would prefer if you created a new issue on GitHub. If you believe there is no bug/issue with the script itself, join the Discord server and ask there https://pterodactyl-installer.se/discord.

**Comment by originalodz** [comment]
Understood. Thank you for your quick replies and obvious interest in helping out. Closing post.
