### ISSUE TITLE
IpTables Issue

### ISSUE THREAD

**Issue by chrlew082** [vilhelmprytz/pterodactyl-installer#147]
@chrlew082 Did you try the canary version of the script (it's not option 0)? I've seen this occur on WSL so I tried it on WSL and it should be solved.

_Originally posted by @vilhelmprytz in https://github.com/vilhelmprytz/pterodactyl-installer/issues/113#issuecomment-761892134_

This error is now resolved, but a new issue has arisen, it’s telling me the iptables are invalid, what should I do?

**Comment by vilhelmprytz** [comment]
What distribution is this? Also, can you provide the full log?

**Comment by chrlew082** [comment]
I am using the option: 6. At the moment I can not provide the full log but I will when I can, I will re-open this when I can find them.
