### ISSUE TITLE
Unsupported version of Debian

### ISSUE THREAD

**Issue by DJKenzoDE** [VilhelmPrytz/pterodactyl-installer#15]
**Describe the bug**
Unsupported Version of Debian

**To Reproduce**
1. clean install
2. install curl over apt install -y curl
3. run script
4. print error that my debian gnu/linux version 9 is unsupported

**Expected behaviour**
I run the script on a fresh isntalled kvm debian 9 server with installed of curl

**OS (please complete the following information):**
 - OS: Debian 9
 - Installation: daemon

**Comment by VilhelmPrytz** [comment]
Thank you for reporting this issue. Should now be solved as of https://github.com/VilhelmPrytz/pterodactyl-installer/commit/9360d512c88af5f9df34e4971b65984ef45689cb. This issue was caused by the changes made in https://github.com/VilhelmPrytz/pterodactyl-installer/issues/13.
