### ISSUE TITLE
panel: APP_ENVIRONMENT_ONLY=true when it should be false

### ISSUE THREAD

**Issue by vilhelmprytz** [vilhelmprytz/pterodactyl-installer#151]
**Describe the bug**
In `/var/www/pterodactyl/.env`, `APP_ENVIRONMENT_ONLY` is `false` when it should be `true` after install.

**To Reproduce**

1. Run the script.
2. Try to edit settings from the web interface.

**Expected behaviour**
I expect `APP_ENVIRONMENT_ONLY` to be `true`.

**Screenshots**
![APP_ENVIRONMENT_ONLY](https://user-images.githubusercontent.com/15460993/106055589-dad77100-60ed-11eb-928d-2fc834c66501.png)

**OS (please complete the following information):**
 - OS: all
 - Installation: panel

**Additional context**
N/A

**Comment by Linux123123** [comment]
A simple `sed` command should do as you can't do this in `php artisan`.

**Comment by vilhelmprytz** [comment]
Or we could use `php artisan p:environment:setup --settings-ui=true`. I will implement this.

**Comment by Linux123123** [comment]
Oh so this is the one setting I was searching for...  Yup it should be enabled by default.
