### ISSUE TITLE
panel: check email address provided

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#157]
**Is your feature request related to a problem? Please describe.**
When you enter an email address, it isn't checked and just passed to `letsencrypt` and `artisan`. It can be invalid and cause problems.

**Describe the solution you'd like**
Check the input with this regex:
```
/^[^\s@]+@[^\s@]+\.[^\s@]+$/
```

**Describe alternatives you've considered**
Entering email address that is correct. :)

**Comment by vilhelmprytz** [comment]
Would you like to implement this regex in the script? I used another regex in #161 and it didn't really handle all use cases very well, but just as long as we can eliminate the obvious ones I think it's a huge improvement :+1:
