### ISSUE TITLE
panel: check OS architecture

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#158]
**Describe the bug**
The script can be run on other architectures then `x86_64`, even though `MariaDB` only supports `x86_64`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the script on 32 bit machine
2. The script tries to install `MariaDB` and can't

**Expected behaviour**
It should check if the OS is `x86_64` and disallow other architectures.

**OS (please complete the following information):**
 - OS: all
 - Installation: panel (wings already checks)

**Additional context**
```[error] The MariaDB Repository only supports x86_64 and aarch64 (detected i686).
[error] The MariaDB Repository supports these Linux OSs, on x86-64 only:
    * RHEL/CentOS 7 & 8
    * Ubuntu 16.04 LTS (xenial), 18.04 LTS (bionic), & 20.04 LTS (focal)
    * Debian 9 (stretch) & 10 (buster)
    * SLES 12 & 15
[error] See https://mariadb.com/kb/en/mariadb/mariadb-package-repository-setup-and-usage/#platform-support```

**Comment by vilhelmprytz** [comment]
Thank you for reporting this. This is definitely not intended behaviour. Can we fetch CPU architecture without using `virt-what`?

**Comment by Linux123123** [comment]
We already have this in `wings` install.
```bash
  MACHINE_TYPE=$(uname -m)
  if [ "${MACHINE_TYPE}" != "x86_64" ]; then # check the architecture
    print_warning "Detected architecture $MACHINE_TYPE"
    print_warning "Using any other architecture than 64 bit (x86_64) will cause problems."

    echo -e -n  "* Are you sure you want to proceed? (y/N):"
    read -r choice

    if [[ ! "$choice" =~ [Yy] ]]; then
      print_error "Installation aborted!"
      exit 1
    fi
  fi
```
It doesn't use `virt-what` for this part.

**Comment by vilhelmprytz** [comment]
> We already have this in `wings` install.
> 
> ```shell
>   MACHINE_TYPE=$(uname -m)
>   if [ "${MACHINE_TYPE}" != "x86_64" ]; then # check the architecture
>     print_warning "Detected architecture $MACHINE_TYPE"
>     print_warning "Using any other architecture than 64 bit (x86_64) will cause problems."
> 
>     echo -e -n  "* Are you sure you want to proceed? (y/N):"
>     read -r choice
> 
>     if [[ ! "$choice" =~ [Yy] ]]; then
>       print_error "Installation aborted!"
>       exit 1
>     fi
>   fi
> ```
> 
> It doesn't use `virt-what` for this part.

Ah, my bad, got a little confused. Yes, that could definitely be used!
