### ISSUE TITLE
some of the packages seem to be missing

### ISSUE THREAD

**Issue by marvinej** [vilhelmprytz/pterodactyl-installer#159]
**Describe the bug**
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Hit:2 http://deb.debian.org/debian buster InRelease
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Hit:4 https://packages.sury.org/php buster InRelease
Ign:5 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu hirsute InRelease
Get:7 http://security.debian.org/debian-security buster/updates/main Sources [177 kB]
Ign:8 http://ppa.launchpad.net/ondrej/php/ubuntu hirsute InRelease
Get:9 http://security.debian.org/debian-security buster/updates/main amd64 Packages [266 kB]
Get:10 https://dlm.mariadb.com/repo/maxscale/latest/debian buster InRelease [3,515 B]
Get:12 http://deb.debian.org/debian buster-updates/main Sources.diff/Index [5,656 B]
Get:13 http://deb.debian.org/debian buster-updates/main amd64 Packages.diff/Index [5,656 B]
Get:14 http://deb.debian.org/debian buster-updates/main Translation-en.diff/Index [3,688 B]
Get:15 http://deb.debian.org/debian buster-updates/main Sources 2021-02-07-1359.56.pdiff [959 B]
Get:16 http://deb.debian.org/debian buster-updates/main amd64 Packages 2021-02-07-1359.56.pdiff [2,302 B]
Get:15 http://deb.debian.org/debian buster-updates/main Sources 2021-02-07-1359.56.pdiff [959 B]
Get:16 http://deb.debian.org/debian buster-updates/main amd64 Packages 2021-02-07-1359.56.pdiff [2,302 B]
Err:17 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu hirsute Release
  404  Not Found [IP: 91.189.95.85 80]
Get:18 http://deb.debian.org/debian buster-updates/main Translation-en 2021-02-07-1359.56.pdiff [1,506 B]
Get:18 http://deb.debian.org/debian buster-updates/main Translation-en 2021-02-07-1359.56.pdiff [1,506 B]
Hit:6 https://downloads.mariadb.com/MariaDB/mariadb-10.5/repo/debian buster InRelease
Err:19 http://ppa.launchpad.net/ondrej/php/ubuntu hirsute Release
  404  Not Found [IP: 91.189.95.85 80]
Hit:11 https://downloads.mariadb.com/Tools/debian buster InRelease
Reading package lists...
E: The repository 'http://ppa.launchpad.net/chris-lea/redis-server/ubuntu hirsute Release' does not have a Release file.
E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu hirsute Release' does not have a Release file.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**OS (please complete the following information):**
 - OS: Debian 10
 - Installation: both

**Additional context**

**Comment by Linux123123** [comment]
The script doesn't add those `ppas`. You aren't running the script on a clean OS.

**Comment by marvinej** [comment]
ok good to know i'll start from square one. i got fed up trying to do the manual setup on their website and found this.
