### ISSUE TITLE
wings: Skip the virtualization warnings

### ISSUE THREAD

**Issue by MichelBaie** [vilhelmprytz/pterodactyl-installer#160]
Add an argument to allow installing on LXC because it works :)

**Comment by sinmineryt** [comment]
Docker in LXC is **not** officially supported by Docker. Many people will have trouble with installing with the script, so I would keep the warning.

**Comment by Linux123123** [comment]
The script is doing what the `pterodactyl` official install guide is doing. In the [System Requirements](https://pterodactyl.io/wings/1.0/installing.html#system-requirements) it says that "*If your provider makes use of Virtuozzo, OpenVZ (or OVZ), or LXC then you will most likely be unable to run Wings*". Based on that we are not allowing to install `wings` when using Virtuozzo, OpenVZ (or OVZ), or LXC.

**Comment by vilhelmprytz** [comment]
The panel may run on LXC and OpenVZ and as far as I know, there is no check that prevents that. Wings, however, require Docker which most likely won't run with LXC or OpenVZ. I am not sure about LXC, but Virtuozzo has "experimental support" that requires the host machine to enable it ([see this](https://wiki.openvz.org/Docker_inside_CT_vz7)).

Closing.

**Comment by MichelBaie** [comment]
Idk if i can re-open this issue, but many hosters are using Proxmox to create Containers LXC. And it's only a box to check to make nesting (Docker) working. Pterodactyl is running perfectly with this box checked. A lot of french hosts are especially allowing docker on their lxc hosting offers.

This is why i proposed to add an argument like --ignore-lxc or others, to allow pterodactyl to be installed on these containers.
A lot of customers are asking for help to manually install Pterodactyl, because they can't use this installation script.

**Comment by MichelBaie** [comment]
I didn't have a lot of skills in Bash to modify the script and ignore this warning, so it's why i asked for it.

**Comment by vilhelmprytz** [comment]
Ah, I see. I'll reopen the issue but I am yet to decide if this is going to be implemented. I see the use case and I understand it's frustrating that the script doesn't let the user override the check. We'll definitely change something, but maybe not in the form of a command line option! :slightly_smiling_face: 

In the meantime, you can remove this line to override the check. https://github.com/vilhelmprytz/pterodactyl-installer/blob/600d8dc78adb0b0069618a5b03cd7469e6778c2c/install-wings.sh#L237

**Comment by MichelBaie** [comment]
Thanks :)
