### ISSUE TITLE
panel/wings: Check FQDN

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#162]
**Is your feature request related to a problem? Please describe.**
Every once in a while there are people who don't see the warning about not using IP's and SSL. If you try to use IP it almost certainly crashes.

**Describe the solution you'd like**
The script would check the entered FQDN and based on the result give options to use letsencrypt / ASSUME SSL.

**Describe alternatives you've considered**
Read the warning.

**Comment by vilhelmprytz** [comment]
If we add a check that verifies whether user input is IP or FQDN, I still think the option to override it should be present. Currently, the `verify-fqdn` script also has the option to override the warning. And IPs do fail the `verify-fqdn` test, so I am not too sure whether introducing another check would actually lead to users not reading the warning?
