### ISSUE TITLE
panel/wings: The script is able to run on Ubuntu 20.10

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#163]
**Describe the bug**
The script doesn't check the minor version of ubuntu. So it can't differentiate between 20.04 and 20.10. This causes the script to fail as 20.10 is not supported and shouldn't be allowed to run the script. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the script
2. See the ubuntu 20.10 is allowed

**Expected behaviour**
Installing on ubuntu 20.10 should not be allowed

**Screenshots**
![image](https://user-images.githubusercontent.com/26341983/108598339-d113f700-7395-11eb-85d9-b23c74c7eedf.png)

**OS (please complete the following information):**
 - OS: Ubuntu 20.10
 - Installation: panel and wings

**Comment by vilhelmprytz** [comment]
What is it about 20.10 that causes the install to fail?

**Comment by sinmineryt** [comment]
> What is it about 20.10 that causes the install to fail?
The redis-server repository doesn't have a release file for ubuntu groovy

**Comment by Linux123123** [comment]
> > What is it about 20.10 that causes the install to fail?
> 
> The redis-server repository doesn't have a release file for ubuntu groovy

No this was not a clean install.

**Comment by Linux123123** [comment]
I haven't tested, so don't really know. Based on `ubuntu20_dep` it all should work fine. The problem is that it is not in the supported list.

**Comment by vilhelmprytz** [comment]
I don't think we should implement a check that denies 20.10. I also don't want it to be added to the supported list since I don't think it's good to encourage users to try the script with 20.10, the LTS version is in most cases better. Did I misunderstand the issue report? Do you think that 20.10 should be denied or should it be added to the supported list? Any arguments for/against either of the options? :slightly_smiling_face:

**Comment by Linux123123** [comment]
Well, my issue was about denying because I thought that it doesn't work, but it clearly should work so that argument is out of the question. I rather just add it to the supported list as it isn't that much different from 20.04 and should just give people more freedom when choosing supported OS. It would only be a problem if it required additional work.

**Comment by vilhelmprytz** [comment]
20.10 is not LTS and I don't think it's worth "officially supporting", is it? It's EOL in [July 2021](https://wiki.ubuntu.com/Releases). I wonder how many people actually read the README, probably not too many... :slightly_smiling_face:

**Comment by Linux123123** [comment]
Then we can just unofficially support it? Leave everything as is and close this issues?

**Comment by vilhelmprytz** [comment]
Unless you have another suggestion, yes, I think so? :slightly_smiling_face: Again, I'd be happy to hear counter-arguments!
