### ISSUE TITLE
Pteroq service has wrong users in CentOS7

### ISSUE THREAD

**Issue by PipeItToDevNull** [vilhelmprytz/pterodactyl-installer#165]
See this bug https://github.com/pterodactyl/panel/issues/2806

When I used this script it set the user as `www-data` in the `pteroq.serivce` file causing the service to fail. CentOS7 uses `nginx` as the user.

**Comment by Linux123123** [comment]
Yes, this is a bug of the script. No one else had this problem so maybe it isn't affecting all installs? We should be able to easily change the user to `nginx` when on Cent OS. Thanks for reporting!

**Comment by vilhelmprytz** [comment]
Thank you for reporting. I will investigate.

**Comment by vilhelmprytz** [comment]
This has now been fixed and the changes are released. Let me know if it's still broken! :+1:
