### ISSUE TITLE
Unsupported OS on debian 10 testing

### ISSUE THREAD

**Issue by Dreaming-Codes** [vilhelmprytz/pterodactyl-installer#167]
**Describe the bug**
The script recognizes debian as unsupported

**To Reproduce**
Steps to reproduce the behaviour:
1. Use debian testing
2. Run the script

**Expected behaviour**
It should normally install the panel and daemon on debian 10 for me

**Screenshots**
![image](https://user-images.githubusercontent.com/10401566/109775899-569f6e80-7c02-11eb-9b9a-4c4b783763f2.png)

**OS (please complete the following information):**
 - OS: Debian 10 testing
 - Installation: both

**Comment by vilhelmprytz** [comment]
Are you using [Debian sid](https://www.debian.org/releases/sid/), the unstable version of Debian?

**Comment by Linux123123** [comment]
No based on what he is saying this is Debian testing. We don't support it, because it is not stable. We only support Debian 10 stable.

**Comment by Dreaming-Codes** [comment]
can you put a flag to manually specify what os you are on?

**Comment by Linux123123** [comment]
No and even if there were this option our script wouldn't really work on Debian testing.

**Comment by Dreaming-Codes** [comment]
Why? Debian testing uses almost same versions of the packages that Ubuntu uses.

**Comment by Linux123123** [comment]
No, if you didn't know, it's not about the versions. If you want to use Ubuntu packages use Ubuntu. The script doesn't support Debian testing. We only support Debian 10.

**Comment by vilhelmprytz** [comment]
Debian `sid` changes over time and is not equivalent to Ubuntu or Debian, although it may currently share a lot of the package versions. :slightly_smiling_face: You can modify the script so that it thinks you are using Ubuntu 20.04 or Debian 10, even though you are not. Closing for now.
