### ISSUE TITLE
Can i rerun the lets encrypt part of the installer

### ISSUE THREAD

**Issue by tankinnwow** [vilhelmprytz/pterodactyl-installer#169]
So, I'm super new to using Linux beyond the basics.

When you run the installer it askes you if you want to configure Lets Encrypt. I did that and everything is working great, but i might need to buy and setup a new domain. I don't want to host my servers on the same domain or addresses as my panel or nodes. Is there a way to rerun that part of the script so it will update the certificates for the panel with the new domain.

Sorry if this is a dumb question, but I'm on the edge of knowledge. Figured i would ask here :)

**Comment by vilhelmprytz** [comment]
Thanks for opening the issue! Unfortunately, the script won't succeed if you run it twice on the same system without wiping everything first (clean system install). Changing the domain and obtaining a Let's Encrypt certificate isn't too complicated however and can be done after completing the install. Look it up online, plenty of guides. We also have a  [Discord server](https://pterodactyl-installer.se/discord) that you can join for support with the script itself. Closing.
