### ISSUE TITLE
Does not work with proxmox

### ISSUE THREAD

**Issue by thephatcrew** [vilhelmprytz/pterodactyl-installer#171]
VM Ubuntu 20.04.2 LTS

pterodactyl@pterodactyl:~$ bash <(curl -s https://pterodactyl-installer.se)
* This script must be executed with root privileges (sudo).
pterodactyl@pterodactyl:~$ sudo bash <(curl -s https://pterodactyl-installer.se)
bash: /dev/fd/63: No such file or directory

I dont think its the script fault but something else but still posting just in case im wrong

**Comment by sinmineryt** [comment]
You need to be logged in as root

**Comment by sinmineryt** [comment]
sudo will not work

**Comment by thephatcrew** [comment]
winner winner checking dinner!!! Also log in as root I had to nano /etc/ssh/sshd_config and add this PermitRootLogin yes
