### ISSUE TITLE
Auto-Deploy tokens not working

### ISSUE THREAD

**Issue by hnyelyze** [vilhelmprytz/pterodactyl-installer#172]
For example: cd /etc/pterodactyl && sudo wings configure --panel-url http://192.168.1.28 --token DDSw73sPPMM2VjTB1jw1Z6bkVd6se0NbVbkmYp4DFjf8CZrn --node 1 
Says that /etc/pterodactyl no such file or directory

**Comment by sinmineryt** [comment]
Create it using
```
mkdir /etc/pterodactyl
```

**Comment by vilhelmprytz** [comment]
Are you sure the script completed the install successfully? The script creates /etc/pterodactyl` automatically, see https://github.com/vilhelmprytz/pterodactyl-installer/blob/c3c57f60bdacae95620f9c35dc32081053528052/install-wings.sh#L332

**Comment by vilhelmprytz** [comment]
Stale issue. Reopen if this is still a problem.
