### ISSUE TITLE
OpenLitespeed

### ISSUE THREAD

**Issue by rafalohaki** [vilhelmprytz/pterodactyl-installer#177]
Please add OpenLitespeed support. Imo its better version of nginx.

**Comment by Linux123123** [comment]
We only support and will support installation with `nginx`. We do not support random web servers people want to use. You can install manually to get support for your wanted web server.

**Comment by vilhelmprytz** [comment]
Thanks for the suggestion. Unfortunately, we only support Nginx at the moment. We have no plans on supporting anything else currently.

**Comment by rafalohaki** [comment]
its not random web server...
booking.com
plesk.com
mailchimp.com
archive.com
joomla.com
mcafee.com
hostinger.com
ioobit.com
lenovo.com
theporndude.com
they are using litespeed. soon everyone is going to use it

**Comment by vilhelmprytz** [comment]
Not even half of the websites you listed are using OpenLiteSpeed. They may be using LiteSpeed; that's not the same thing. Either way, it's unfortunately not about whether people are using LiteSpeed or not and rather whether we're able to support it or not :slightly_smiling_face:
