### ISSUE TITLE
Some packages could not be installed.

### ISSUE THREAD

**Issue by Maelep** [vilhelmprytz/pterodactyl-installer#183]
**Describe the bug**
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mariadb-server : Depends: mariadb-server-10.3 (>= 1:10.3.29-0ubuntu0.20.04.1) but it is not going to be installed
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a fresh Ubuntu 20.04 VPS.
2. Follow this tutorial: [Initial Server Setup with Ubuntu 20.04](https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-20-04)
3. Follow this tutorial: [How To Install Linux, Apache, MySQL, PHP (LAMP) stack on Ubuntu 20.04](https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-20-04)
3. Follow this tutorial: [How To Secure Apache with Let's Encrypt on Ubuntu 20.04](https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-20-04)
4. Try to install Panel only (1).

**Expected behaviour**
Install the panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/53207714/118512143-d681a300-b732-11eb-9fd9-ce3c77615326.png)

**OS (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation: panel

**Additional context**
Fresh Ubuntu 20.04 + Basic OS setup + LAMP + SSL.

**Comment by sinmineryt** [comment]
This script needs to run on a clean system.

**Comment by Maelep** [comment]
I have to rent a machine to install the panel only? Can I install LAMP after this script?

**Comment by sinmineryt** [comment]
Since the script is using nginx, you should not install apache after doing this. The script automatically installs mariadb, nginx and php for you.

**Comment by Maelep** [comment]
Ok, it was so hard for me to install make these tutorial that now I have to use nginx and mariadb :(

**Comment by sinmineryt** [comment]
MariaDB is basically the same as MySQL.

**Comment by Linux123123** [comment]
The script install LEMP stack in which:
L - linux
E - nginx
M - mariadb
P - php

**Comment by Maelep** [comment]
Ok, I'll refresh my VPS and try to host my website + panel.

**Comment by vilhelmprytz** [comment]
This is not a problem with the script. Use the [Discord server](https://pterodactyl-installer.se/discord) for support with the script. Closing.
