### ISSUE TITLE
getaddrinfo failed

### ISSUE THREAD

**Issue by Shaneajm** [vilhelmprytz/pterodactyl-installer#189]
**Describe the bug**
Upon installing the panel, `AbstractConnection.php` has an issue with the Redis connection and stops the installer.

**To Reproduce**
Steps to reproduce the behaviour:
1. Fresh Debian 10 Installation
2. Run the installer (I selected both the panel and wings for the install)
4. Error occurs.

**Expected behaviour**
Installation will continue and install the application as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/9031327/119402070-3b884c00-bc91-11eb-8402-be4298c68baf.png)

**OS (please complete the following information):**
 - OS: Debian 10
 - Installation: panel

**Additional context**

**Comment by vilhelmprytz** [comment]
Thanks for reporting. Can you provide the contents of `/etc/hosts`?

**Comment by Shaneajm** [comment]
```
127.0.0.1    localhost
127.0.1.1    us

# The following lines are desirable for IPv6 capable hosts
::1          localhost ip6-localhost ip6-loopback
ff02::1      ip6-allnodes
ff02::2      ip6-allrouters
```

**Comment by vilhelmprytz** [comment]
What's the hostname of your server?

**Comment by vilhelmprytz** [comment]
I don't think the script is broken. Are you sure your `/etc/hosts` is configured correctly? The hostname of your server should be in that file, pointing to a loopback IP.

**Comment by Shaneajm** [comment]
It was an OS issue, got it fixed now :)
