### ISSUE TITLE
When running the scripts the database uses a blank password

### ISSUE THREAD

**Issue by cantercrow** [VilhelmPrytz/pterodactyl-installer#19]
**Describe the bug**
When running the panel install script and getting to the database setup part it says that the script should have already asked you to set the database password which it has not, for the password I just hit enter, if I enter a password set for the pterodactyl user it shows an error

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the panel script 
                  bash <(curl -s https://raw.githubusercontent.com/VilhelmPrytz/pterodactyl-installer/master/install-panel.sh)

**Expected behaviour**
Asked to set the database root access password from blank to a password

**Screenshots**
N/A

**OS (please complete the following information):**
 - OS: Ubuntu 18.04 x64
 - Installation: [panel]

**Additional context**
I have run the scripts on two separate machines to test.

**Comment by VilhelmPrytz** [comment]
The script does ask for a database password. I'm not sure if you're referring to the MySQL root password?

**Comment by VilhelmPrytz** [comment]
Ah, I think I understand what you mean. Is it at this part of the script you are referring about?

```
* Downloaded pterodactyl panel files & installed composer dependencies!
* Creating MySQL database & user..
* The script should have asked you to set the MySQL root password earlier (not to be confused with the pterodactyl database user password)
* MySQL will now ask you to enter the password before each command.
* Performing MySQL queries..
* Create MySQL user.
Enter password: 
* Create database.
Enter password: 
* Grant privileges.
Enter password: 
* Flush privileges.
Enter password: 
* MySQL database created & configured!
```

As the script is being run as root, a root password is not required (I think). You should be able to just press enter, leaving the field empty. Perhaps this should be stated somewhere in the script.

Let me know if it works.

**Comment by VilhelmPrytz** [comment]
I've improved this. Root passwords are no longer required to be entered during MySQL setup (performing queries) for all installations except CentOS.
