### ISSUE TITLE
Error: retrieving gpg key timed out.   

### ISSUE THREAD

**Issue by Alis-Dev-idn** [vilhelmprytz/pterodactyl-installer#191]
Install in ubuntu 20.04,

**Comment by Alis-Dev-idn** [comment]
.

**Comment by ritzcracr** [comment]
is there a way to solve this?
I am getting trhe sam error on 20,04 with a fresh install

**Comment by vilhelmprytz** [comment]
This is most likely not a problem with the script. Refer to the [Discord server](https://pterodactyl-installer.se/discord) for support with the script.
