### ISSUE TITLE
Lightsail stop, start messes up. Add scripts

### ISSUE THREAD

**Issue by siliconhippy** [vilhelmprytz/pterodactyl-installer#195]
**Describe the bug**

Hi Vilhelm !

1. Your script (from about 20 days ago, last but one revision) after following additions ran well with Minecraft Server on my AWS Lightsail Ubuntu 20.04 2GB RAM, 60 GB SSD $10 instance.

a. Manually add all open ports to Lightsail Networking Firewall menu, even after ufw commands !

b. sudo ufw allow in on pterodactyl to  172.18.0.1 port 25565 proto tcp

(and equivalent for other game server ports.)

c. sudo  sysctl enable --now docker
sudo reboot

[Courtesy peterodactyl.io docs.]

2. The problem:

I stopped the Lightsail instance to make a snapshot. Then made a new instance of the snapshot to add a CSGO server.

But the Configuration pasting ( overwrite = y) gave me errors and then the whole thing seemed messed up, likely because of stopping the original instance.

When I looked at the original instance after restarting it, MC couldn't restart, and running "sudo wings --debug "showed many errors. 

Unluckily I cannot seem to be able to copy paste the whole part from the ssh screen. But this seems the only error:

-------------
FATAL: [Jun 12 23:42:24.776] failed to configure HTTP server error=liste
n tcp 0.0.0.0:8080: bind: address already in use

Stacktrace:
listen tcp 0.0.0.0:8080: bind: address already in use
github.com/pterodactyl/wings/cmd.rootCmdRun
/home/runner/work/wings/wings/cmd/root.go:347
github.com/spf13/cobra.(*Command).execute
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go
:854
github.com/spf13/cobra.(*Command).ExecuteC
/home/runner/go/pkg/mod/github.com/s
-------------------

I will now reinstall using your script again. But do you think you can update your useful script for restarts etc?

**Comment by sinmineryt** [comment]
It seems like wings is already running in the background, or another application is using the port 8080. Check what application is using port 8080 by running
```sh
netstat -tulpn | grep 8080
```

**Comment by sinmineryt** [comment]
Also if you want faster support, [join the discord server](https://discord.gg/YQJDMarS63)!

**Comment by vilhelmprytz** [comment]
This does not seem to be a problem with the script. Once Pterodactyl is successfully installed, the system can be restarted and the installation should be persistent (if that was what you were asking about). Join the [Discord server](https://pterodactyl-installer.se/discord) for support with the script. Closing, reopen if you believe there is an error with the script.
