### ISSUE TITLE
Add hostname to /etc/hosts

### ISSUE THREAD

**Issue by MichelBaie** [vilhelmprytz/pterodactyl-installer#198]
Hi :)

I had problems with my networking solution and solved it by adding my panel & node hostname to /etc/hosts
It redirect my traffic directly at 127.0.0.1

I think it will not cause troubles to the script and can help some other peoples.

Todo : 

add `panel.hostname 127.0.0.1 `  to /etc/hosts

**Comment by vilhelmprytz** [comment]
Can you explain further why adding `panel.hostname 127.0.0.1` to `/etc/hosts` solved networking issues? Do you have both the panel and Wings running on the same machine?

**Comment by MichelBaie** [comment]
I had panel and wings running on the same machine,

(values are for example)
My machine ip is 52.168.X.X and the dns entry is 52.168.X.X (same)
My machine can't talk to his external ip (52.168.X.X) it's due to [my network solution for self hosting](https://michelbaie.github.io/Tutos/OVH) wich work wells but have some problems.

When i define the dns entry (panel.hostname) to 127.0.0.1 it will not contact external ip but directly the localhost.
And it fixed my problem.

I don't think it will change a lot of things to other peoples but it fixed my problems and for other one wich are using my solution.

**Comment by vilhelmprytz** [comment]
If you set your hostname to an FQDN at install then the hostname will already be defined in `/etc/hosts` as you described (correct me if I'm wrong). I don't know, but does the panel need to speak to itself? Not all people run the panel and wings on the same machine. The wings script is completely separate from the panel script meaning the wings script will not know what FQDN was configured in the panel script (if they run on the same machine).
