### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ragemalik** [vilhelmprytz/pterodactyl-installer#199]
Hello,

I have a question is there like a test pannel where I can see how it works? As an admin?
And when I make a server and give access to people to mske databases how many connections csn the database have?

**Comment by rugalservidores** [comment]
There is no test panel you will need to install one to test all these things.

**Comment by Ragemalik** [comment]
Oh okay but do you know the answer to my question about the databases? And can u make other databases like mariadb not just mysql

**Comment by vilhelmprytz** [comment]
This is simply a script to install  [Pterodactyl](https://pterodactyl.io). Refer to the official project for questions about the software itself. For support with the script, join the [Discord server](https://pterodactyl-installer.se/discord). Closing.
