### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by vilhelmprytz** [vilhelmprytz/pterodactyl-installer#20]
**Describe the feature you'd like**
Improve user experience by color coding messages, indicating progress using animations and generally rewriting messages printed to the user.

**Comment by MrFlacko** [comment]
I reckon I can take a shot at this, I did this with the last script
It will take a couple of days tho.

**Comment by Linux123123** [comment]
Could you wait a little while? There is a panel PR in the review faze and will be merged ASAP. But you can do this on wings.

**Comment by MrFlacko** [comment]
no worries

**Comment by vilhelmprytz** [comment]
@MrFlacko Being "blocked" by two other PRs is no longer the case. Go fork! I'm also not too sure there is much to do on the project regarding UX/UI. Feel free to submit any new UI/UX changes since there are parts that could do with improvement, but not enough to have such a vague issue as this one kept open. Closing.
