### ISSUE TITLE
wings: Script does not detect openvz and lxc at the same time

### ISSUE THREAD

**Issue by sinmineryt** [vilhelmprytz/pterodactyl-installer#200]
**Describe the bug**
Docker can't run on `openvz` and `lxc`. The script detects if the user is running `openvz` or `lxc` but not if they are using them at the same time:
```php
$ virt-what
openvz
lxc
```
**To Reproduce**
Get a machine using `lxc` and `openvz` and try to install wings.

**Expected behaviour**
The script should complain about the virtualization type

**Additional context**
In code:
https://github.com/vilhelmprytz/pterodactyl-installer/blob/8febae1a48d60ecc2fd68c5eda4657b6eb9e8e42/install-wings.sh#L240-L244
Discord:
https://discord.com/channels/682342331206074373/682356044898500634/857019203088678923

**Comment by Linux123123** [comment]
The fix might be as simple as checking for `*openvz* | *lxc*)`, instead of checking for `openvz | lxc)`. But not gonna lie it's an oddball case.

**Comment by vilhelmprytz** [comment]
Do you run LXC containers inside OpenVZ or the other way around?

**Comment by sinmineryt** [comment]
I don't run any of these. I just opened this issue due to the bug reports
in the discord server.
Check the discord link in the original issue


Vilhelm Prytz ***@***.***> schrieb am Fr., 2. Juli 2021,
20:58:

**Comment by sinmineryt** [comment]
Update: someone has got another type of LXC
```
$ virt-what
virtual machine lxc
```
https://discord.com/channels/682342331206074373/718551748431577139/863723503950102528
