### ISSUE TITLE
CNAME records not supported

### ISSUE THREAD

**Issue by jobhh** [vilhelmprytz/pterodactyl-installer#201]
**Is your feature request related to a problem? Please describe.**
Using CNAME records results in the script claiming a domain does not point to the proper IP address.

**Describe the solution you'd like**
Support CNAME records.

**Describe alternatives you've considered**
None.

**Additional context**
Ran the script on a clean Debian 10 installation

This is the logging for an example where sub.primarydomain.com points to sub2.diffrentdomain.com, which points to sub3.duckdns.org, which points to 10.0.0.22:

```
* I agree that this HTTPS request is performed (y/N): y
* Resolving DNS for sub.primarydomain.com
* The DNS record (sub2.diffrentdomain.com.
sub3.duckdns.org.
10.0.0.22) does not match your server IP. Please make sure the FQDN games.wehlan.nl is pointing to the IP of your server, 10.0.0.22
* If you are using Cloudflare, please disable the proxy or opt out from Let's Ecnrypt.
* Proceed anyways (your install will be broken if you do not know what you are doing)? (y/N):
```

Please note that the IP does actually show up in the DNS record, alongside the CNAME records.

**Comment by vilhelmprytz** [comment]
Thank you for reporting this. This should definitely be fixed and the current behavior is undesirable.
