### ISSUE TITLE
Nginx proxy manager/OMV now broken

### ISSUE THREAD

**Issue by bchilton9** [vilhelmprytz/pterodactyl-installer#214]
This installer changes settings in nginx and now I can no longer access my OMV web UI or any of my hosts with nginx proxy manager. I have tried removing the pterodactyl config and restoreing the default site in nginx sites enabled and it did not work. Any advice on what files where changed so I can revert them back. Thank you

**Comment by Linux123123** [comment]
The script doesn't change any of the `nginx` default files. It adds the `pterodactyl.conf` and removes the symlink to the default configuration. I don't know any reason why you would be using default configuration, but to symlink it back you run 
```bash
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
```

**Comment by bchilton9** [comment]
I tried changing it back to see if it would fix my problem. Everything was fine before I ran the installer

**Comment by vilhelmprytz** [comment]
The installer does not touch any of the Nginx default configuration files. Did you use the same `server_name` for your other project and Pterodactyl?

**Comment by bchilton9** [comment]
I reinstalled the system.
