### ISSUE TITLE
Suggestion: Automatically create user for database host

### ISSUE THREAD

**Issue by sinjs** [vilhelmprytz/pterodactyl-installer#220]
**Is your feature request related to a problem? Please describe.**
X

**Describe the solution you'd like**
When asking for the database username, also ask if the user would want to set up another user for pterodactyl database hosts, if yes, ask for the username.

**Describe alternatives you've considered**
X

**Additional context**
This will make it easier for the user to create a database host.

**Comment by Linux123123** [comment]
This has already been talked over in the #105

**Comment by sinmineryt** [comment]
I could try and implement this

**Comment by Linux123123** [comment]
I am not sure how it needs to be implemented. We kinda never ended up deciding how it would work with @vilhelmprytz

**Comment by vilhelmprytz** [comment]
Do I understand correctly that #222 is implementing what we discussed in #105?

**Comment by Linux123123** [comment]
Yes. I think we can close #105 in favor of #222 as this is more clear where is the problem, and how to solve it.
