### ISSUE TITLE
Ubuntu 21.04 not supported

### ISSUE THREAD

**Issue by VibeGAMESNL** [vilhelmprytz/pterodactyl-installer#221]
Ubuntu 21.04 not supported. However pterodactyl runs fine on it.

Please also support Ubuntu 21.04

**Comment by Linux123123** [comment]
Please read previous issues before opening a new one. We just closed the exact same issue 6 days ago.

#215

**Comment by rugalservidores** [comment]
<html>
<body>
<h3 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(240, 243, 246); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(10, 12, 16); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Supported panel operating systems and webservers</h3>

Operating System | Version | nginx support | PHP Version
-- | -- | -- | --
Ubuntu | 14.04 | 🔴 |  
  | 16.04 | 🔴 * |  
  | 18.04 | ✅ | 8.0
  | 20.04 | ✅ | 8.0
Debian | 8 | 🔴 * |  
  | 9 | ✅ | 8.0
  | 10 | ✅ | 8.0
CentOS | 6 | 🔴 |  
  | 7 | ✅ | 8.0
  | 8 | ✅ | 8.0


</body>
</html>

Are you sure?

**Comment by Linux123123** [comment]
Read the issue #215

**Comment by vilhelmprytz** [comment]
As mentioned by @Linux123123, this has been discussed before. 21.04 is not LTS and is not listed by the Pterodactyl team as "supported" even though it may run perfectly. I would recommend using 20.04 LTS instead. Closing.
