### ISSUE TITLE
How To Reinstall Pterodactyle panel?

### ISSUE THREAD

**Issue by aril3721** [vilhelmprytz/pterodactyl-installer#223]
Like A Title I Want Reinstall My Pterodactyl Panel Because Too much error. And I Want To Reinstal Fresh Pterodactyl Panel. If This Possible How I Do That?

**Comment by vilhelmprytz** [comment]
@Linux123123 is working on an uninstallation script that will hopefully be merged soon so it can be used. In the meantime, the best solution is probably to reinstall the OS of your machine. This is not really an issue with the script, so I will convert this into a discussion thread! 👍
