### ISSUE TITLE
wings: certbot can't be installed without epel-release

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#229]
**Describe the bug**
CentOS 7 (and probably 8) doesn't have `epel-release` installed prior to installing `certbot` on `wings` installation

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the wings script on CentOS 7
2. Choose to use lets encrypt
3. See how it just doesn't do anything

**Expected behaviour**
Working `certbot`

**OS:**
 - OS: CentOS
 - Installation: wings

**Comment by vilhelmprytz** [comment]
Have you verified that this is the case? I currently have no good method of testing this.

**Comment by Linux123123** [comment]
Install `wings` without panel on a fresh install of CentOS 7, and I am pretty sure it will fail to install `certbot` and get certificates.
