### ISSUE TITLE
Install MariaDB on daemon installations

### ISSUE THREAD

**Issue by DAThosting** [VilhelmPrytz/pterodactyl-installer#23]
**Is your feature request related to a problem? Please describe.**
Missing database server on the daemon.

**Describe the solution you'd like**
Add an option to install a database, such as MariaDB.

**Comment by VilhelmPrytz** [comment]
I am not quite sure what you are referring to, the script already installs MariaDB?

**Comment by DAThosting** [comment]
Not on a daemon/node.
The DB only will be installed on the panel itself.

**Comment by VilhelmPrytz** [comment]
Oh, you meant the daemon itself. An option to install it could be added, yes. I will work on it if I get the time to. Feel free to try and implement this yourself, and send a pull request :smile:

**Comment by VilhelmPrytz** [comment]
My bad didn't mean to close the issue.

**Comment by FrozenPvPs** [comment]
Do you want it to set up MariaDB on the node for it to be hooked up to the panel as a database node?

**Comment by VilhelmPrytz** [comment]
If it is MariaDB on the daemon you're referring to, it should be fairly straight-forward to implement this (install MariaDB and create a user with permissions to create databases/users). I reckon it should be optional whether the script should install it or not.

If anyone has the time to do this, feel free to send a pull request!

**Comment by VilhelmPrytz** [comment]
This has now been implemented. Let me know if it works.
