### ISSUE TITLE
Debian 11 Support

### ISSUE THREAD

**Issue by LordRofl** [vilhelmprytz/pterodactyl-installer#230]
Debian 11 aka Bullseye was released yesterday.

Support for it would be great 👍🏻

**Comment by Linux123123** [comment]
It will be supported, just not that quickly. I think at the same time that we start supporting 11 we should drop support for 9, because it is coming to it's EOL (~2022).

**Comment by vilhelmprytz** [comment]
This is definitely on our todo list.

**Comment by vilhelmprytz** [comment]
This will be included in next release.
