### ISSUE TITLE
[Suggestion] Add an option Let's Encrypt to use DNS validation

### ISSUE THREAD

**Issue by Bocephus** [vilhelmprytz/pterodactyl-installer#235]
Integrating Let's Encrypt is an awesome feature, though I would prefer not to open port 80, and just use DNS validation.

Ideally this would then provide a selection option for HTTP/DNS validation

**Comment by vilhelmprytz** [comment]
Thank you for submitting this issue. May I ask why you would not want to have port 80 open but 443 (HTTPs) open?

**Comment by Bocephus** [comment]
I'd rather not have either port open if I don't need to.  Most of the other services I host internally use DNS validation, which outside of having the proper API info for your external DNS provider, simply requires a txt entry added to your public DNS domain.

**Comment by Linux123123** [comment]
How are you using SSL with both ports closed? The DNS validation method is a lot harder than the one we are using right now.

But that being said, certificates made that way are wildcard (*.domain.com) and that might be good.

**Comment by Bocephus** [comment]
Generally speaking, I don't host anything that is accessible from the internet on port 80.  As for Pterodactyl, I currently have no intentions of hosting it externally on port 80 if I can get away with it. Only on via 443.

Also, the DNS validation can be used for both wildcard and regular named certificates. I use the DNS validation for my HAProxy, specifically for the wildcard functionality that you can use with the DNS validation.

I agree, it is likely much more difficult to code adding the DNS option, and I may be the only one interested if so, I'd say its not worth the effort.

**Comment by vilhelmprytz** [comment]
Would you mind explaining why blocking port 80 is important? If I can understand the use case I might be able to understand if more people would like this feature. If port 80 is blocked but port 443 isn't, then people are going to have to explicitly visit the HTTPS version of your panel as opposed to just visiting the HTTP version and being instantly redirected. If security is a concern, just use HSTS. And I think it's fair to say that wildcard certificates are for most people using this script irrelevant, so I don't think it's worth implementing for that reason but I do understand why DNS validation is required then :slightly_smiling_face:

**Comment by Bocephus** [comment]
Wildcard certificates have nothing to do with this request. DNS validation does not necessarily mean that you are requesting a wildcard certificate. Its true that DNS validation is the only method that allows you to request a wildcard certificate, but it can be used for regular single name certificates as well.

The advantage of using DNS validation, is that as an admin I only need to create a single public facing CNAME, which can be used for all DNS validated certificates for Let's Encrypt. Both internal only certificates, as well as externally accessible certificates.

**Comment by vilhelmprytz** [comment]
Yes, I am fully aware that DNS validation might be used for single-name certificates as well :slightly_smiling_face:. Would you mind explaining this setup with "single public-facing CNAME" a bit further?

**Comment by vilhelmprytz** [comment]
Closing this for now. The interest for DNS validation in this script has been low, please feel free to reopen if there is still an interest for this.
