### ISSUE TITLE
HELPPPPPPPPPPPP

### ISSUE THREAD

**Issue by Sintzy** [vilhelmprytz/pterodactyl-installer#246]
/dev/fd/63
![image](https://user-images.githubusercontent.com/69687594/132247644-b1ebd1b8-4506-4a9a-8de9-19df9c3dbcc9.png)

**Comment by Higor-D** [comment]
Hi, use sudo su first, and after run script again.

**Comment by anewplayerfr** [comment]
execute :

sudo su

and 

bash <(curl -s https://pterodactyl-installer.se)
