### ISSUE TITLE
Autoload.php error

### ISSUE THREAD

**Issue by notacoderr** [VilhelmPrytz/pterodactyl-installer#25]
**Describe the bug**
Most files / configurations doesn't go through since there's a missing file/directory error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Simply install it

**Expected behaviour**
Should go well

**Screenshots**
![image](https://user-images.githubusercontent.com/38270548/73705968-afa38700-4710-11ea-99ab-5682f6e442ee.png)

**OS (please complete the following information):**
 - OS: Ubuntu [Cosmic]
 - Installation: [panel]

**Additional context**

**Comment by VilhelmPrytz** [comment]
Can you post the full log? I can't really understand what's gone wrong by looking at your screenshot.

**Comment by notacoderr** [comment]
I kinda of reset the vps, but in my understanding it has failed to open autoload.php which is when i checked the path, it's really not there. so it's probably the script before it failed to write the autoload.php

**Comment by VilhelmPrytz** [comment]
> I kinda of reset the vps, but in my understanding it has failed to open autoload.php which is when i checked the path, it's really not there. so it's probably the script before it failed to write the autoload.php

Can you try and re-create the issue? I am not able to help you with the information you've given so far, sorry.

**Comment by VilhelmPrytz** [comment]
Closing this issue for now. If you're still having trouble, please re-open the issue with further information.
