### ISSUE TITLE
A way to create and apply git patches to pterodactyl installation

### ISSUE THREAD

**Issue by waseem-h** [vilhelmprytz/pterodactyl-installer#252]
**Is your feature request related to a problem? Please describe.**
A way to create and apply git patches for custom addons / plugins for pterodactyl

**Describe the solution you'd like**
Instead of download the release panel.tar.gz file, maybe clone the whole repo with the version tag?

**Describe alternatives you've considered**
Alternative is to delete everything from /var/www/pterodactyl folder and clone the repo manually and rebuild all the resources using the documentation and then apply or create patches

**Additional context**
An example is applying these patches over the stock installation: https://github.com/Fredthedoggy/FrogPanel
This only works if pterodactyl is cloned via git

**Comment by Linux123123** [comment]
Duplicate of #236

**Comment by vilhelmprytz** [comment]
Closing because of duplicate issue, this is something we should work on.
