### ISSUE TITLE
Password SQL base KO with $ symbol

### ISSUE THREAD

**Issue by Allread** [vilhelmprytz/pterodactyl-installer#253]
**Describe the bug**
Hello

When installing the script, at the request of the SQL database password, I had a "$" symbol in the password.
I was unable to complete the installation.

It does not support "$"

**To Reproduce**
In "password SQL", type password with "$" symbol

**Expected behaviour**
Installation complête

**OS (please complete the following information):**
 - OS : Ubuntu 1804
 - Installation: panel

**Comment by Linux123123** [comment]
This issue is related with #156
The thing is that `read` automatically escapes all user input.

**Comment by vilhelmprytz** [comment]
Can you reproduce this error on other distros? The script nowadays logs the entire installation process to `/var/log/pterodactyl-installer.log`, would you be able to include this log output?

**Comment by Linux123123** [comment]
Can't reproduce on Ubuntu Jammy using the canary version of the script. Please reopen if the issue persists.
