### ISSUE TITLE
Error installing panel

### ISSUE THREAD

**Issue by TimyIsCool** [vilhelmprytz/pterodactyl-installer#256]
**Describe the bug**
Failure when running install panel.sh script
![image](https://user-images.githubusercontent.com/74112751/137602359-6a3a2170-96f1-4767-b245-c69d95cc6da8.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the panel installer and fill all info, near the end is where it happens

**Expected behaviour**
Should work

**Screenshots**

**OS (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation: panel

**Additional context**

**Comment by vilhelmprytz** [comment]
Can you provide the contents of `/var/www/pterodactyl-installer.log`?

**Comment by TimyIsCool** [comment]
> Can you provide the contents of `/var/www/pterodactyl-installer.log`?

sorry, I reinstalled the os but I think the problem was me doing "TG Server" for the database names (Without the "")
