### ISSUE TITLE
/dev/fd/62: line 293: virt-what: command not found

### ISSUE THREAD

**Issue by AamiRobin** [vilhelmprytz/pterodactyl-installer#258]
######################################################################
* Pterodactyl Wings installation script @ v0.8.1
*
* Copyright (C) 2018 - 2021, Vilhelm Prytz, <vilhelm@prytznet.se>
* https://github.com/vilhelmprytz/pterodactyl-installer
*
* This script is not associated with the official Pterodactyl Project.
*
* Running debian version 11.
* Latest pterodactyl/wings is v1.5.3
######################################################################
* debian 11 is supported.
* Installing virt-what...
Selecting previously unselected package virt-what.
(Reading database ... 27890 files and directories currently installed.)
Preparing to unpack .../virt-what_1.19-1_amd64.deb ...
Unpacking virt-what (1.19-1) ...
Setting up virt-what (1.19-1) ...
Processing triggers for man-db (2.9.4-2) ...
/dev/fd/62: line 293: virt-what: command not found

**Comment by Linux123123** [comment]
This is because your specific installation does't have `sbin` in `PATH`. As a temporary solution you can use
```bash
export PATH="$PATH:/sbin:/usr/sbin"
```
And run `wings` script again

**Comment by vilhelmprytz** [comment]
May I ask, how did you become root on your system? Did you login as `root` directly or did you login as a normal user and use `sudo su` or `sudo -i`?

**Comment by AamiRobin** [comment]
yes I run su to get root user

**Comment by vilhelmprytz** [comment]
Just `su` or `su - root`? Try `sudo -i` and see if that works.

**Comment by AamiRobin** [comment]
> 
> 
> This is because your specific installation does't have `sbin` in `PATH`. As a temporary solution you can use
> 
> ```shell
> export PATH="$PATH:/sbin:/usr/sbin"
> ```
> 
> And run `wings` script again

Thank you its fix it

**Comment by AamiRobin** [comment]
Thank you. I really appreciate you guys.

**Comment by AamiRobin** [comment]
Thank you. I really appreciate you guys.
