### ISSUE TITLE
CORS Errors when adding node to default panel

### ISSUE THREAD

**Issue by icodesdeveloper** [vilhelmprytz/pterodactyl-installer#260]
**Describe the bug**
When you install the Panel and add a node I will get CORS errors for communication to the node. The problem exists in a non correct default Nginx vhost in the installer.
**To Reproduce**
Steps to reproduce the behaviour:
Install the panel with the script
Add any node, in our case it was on the same host.
Node will not work(see browser console) ->Cors errors.

**Expected behaviour**
No CORS errors should be retrieven, the problem exists in the default vhost. The problem was fixed by adding these lines:

add_header Strict-Transport-Security "max-age=15768000; preload;";
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
add_header X-Robots-Tag none;
add_header Content-Security-Policy "frame-ancestors 'self'";

**OS (please complete the following information):**
 - OS: Ubuntu server 20.04
 - Installation: Panel and Wings

**Comment by vilhelmprytz** [comment]
Interesting. What was your setup here, panel and Wings using different hostnames? I haven't had a problem with it before since I thought the wings web server handled sending the correct headers.

**Comment by Linux123123** [comment]
Yes this is a problem as our [nginx configuration template](https://github.com/vilhelmprytz/pterodactyl-installer/blob/master/configs/nginx.conf) doesn't have those headers.

**Comment by vilhelmprytz** [comment]
We use the default configuration files as recommended by the Pterodactyl team (with some minor adjustments). I haven't had a problem with this before, can you provide us with more details about your specific setup?

**Comment by vilhelmprytz** [comment]
This is most likely not a problem with the script, closing for now. Reopen if this is not the case!
