### ISSUE TITLE
Can't use the Script on Debian. "Release file for ... is expired"

### ISSUE THREAD

**Issue by FACHRi2007** [vilhelmprytz/pterodactyl-installer#261]
######################################################################
* Pterodactyl Wings installation script @ v0.8.1
*
* Copyright (C) 2018 - 2021, Vilhelm Prytz, <vilhelm@prytznet.se>
* https://github.com/vilhelmprytz/pterodactyl-installer
*
* This script is not associated with the official Pterodactyl Project.
*
* Running debian version 10.
* Latest pterodactyl/wings is v1.5.3
######################################################################
* debian 10 is supported.
* Installing virt-what...
E: Release file for http://debian-archive.trafficmanager.net/debian-security/dists/buster/updates/InRelease is expired (invalid since 3h 46min 2s). Updates for this repository will not be applied.

**Comment by Linux123123** [comment]
Not related to the script, you are using repositories which are not updated and so are expired.

**Comment by FACHRi2007** [comment]
> expired

So How to Fix it? I'm New in Linux Scene

**Comment by vilhelmprytz** [comment]
Might be that your repository is not up-to-date, but could also be that your clock is not set correctly. Install a clean version of Debian, preferably using an ISO from their website.

This is not a problem with the script. Refer to the Discord server for script-related questions. Closing.
