### ISSUE TITLE
/usr/sbin missing in $PATH causes script to fail when script tries to run virt-what

### ISSUE THREAD

**Issue by Warbolt** [vilhelmprytz/pterodactyl-installer#262]
hey, 

i don't know but i had issues with virt-what at line 293. 
it doesn't worked for me (freshly installed Debian 10).

My solution:
`git clone https://github.com/vilhelmprytz/pterodactyl-installer.git`
`nano install-wings.sh`
go to line 293 and add `sudo` to virt_serv=$(_**sudo**_ virt-what) -> save + exit
`./install.sh`

after that it worked for me. maybe for some other this is an issue, too.

---------------------------------------------------------------------------------
update: sorry, nvm didn't worked.

**Comment by vilhelmprytz** [comment]
Can you please provide logs for the problem you are experiencing?

**Comment by AamiRobin** [comment]
This is because your specific installation doesn't have sbin in PATH. As a temporary solution, you can use

export PATH="$PATH:/sbin:/usr/sbin"

And run wings script again

**Comment by Linux123123** [comment]
With the amount of problems we have I think we should just ```export PATH="$PATH:/sbin:/usr/sbin"``` in the script by default.

**Comment by ZEROPOINTBRUH** [comment]
* Installing virt-what...
/dev/fd/62: line 311: virt-what: command not found

**Comment by vilhelmprytz** [comment]
I assume this issue depends on which way you became root on your system (i.e. `sudo -i`, `sudo su`, just directly logging in as root, etc).

@Linux123123 I don't think adding `export PATH="$PATH:/sbin:/usr/sbin"` would be too harmful, the other option is to simply run `/usr/sbin/virt-what` directly. Either way, this should be fixed.

**Comment by vilhelmprytz** [comment]
fixed in #310
