### ISSUE TITLE
nginx can't find the let's encrypt keys

### ISSUE THREAD

**Issue by Tysseract** [vilhelmprytz/pterodactyl-installer#263]
(Debian 11) I went through the command line setup process and nginx won't start because there are no SSL keys even though I went through the whole Let's Encrypt thing.
```
...skipping...
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2021-11-15 00:29:27 PST; 16h ago
       Docs: man:nginx(8)
    Process: 25386 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
        CPU: 10ms

Nov 15 00:29:27 ZenSY systemd[1]: Starting A high performance web server and a reverse proxy server...
Nov 15 00:29:27 ZenSY nginx[25386]: nginx: [emerg] cannot load certificate "/etc/ssl/sub.domain.tld.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/sub.domain.tld
Nov 15 00:29:27 ZenSY nginx[25386]: nginx: configuration file /etc/nginx/nginx.conf test failed
Nov 15 00:29:27 ZenSY systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Nov 15 00:29:27 ZenSY systemd[1]: nginx.service: Failed with result 'exit-code'.
Nov 15 00:29:27 ZenSY systemd[1]: Failed to start A high performance web server and a reverse proxy server.

```

**Comment by vilhelmprytz** [comment]
Seems to me like you did not use the "automatic Let's Encrypt certificate" feature that exists in the script. If you chose to use another SSL certificate, then you need to make sure that the certificate is present. I can see that Nginx tries to look for certificates at `/etc/SSL/sub.domain.tld`. Make sure your certificate files are present there. Also `sub.domain.tld` looks like the domain you are trying to use, it does not look like a valid domain name to me.

This is not a problem with the script, refer to the Discord server for help with the script. Closing.

**Comment by JoeLago** [comment]
Somehow the panel was working for me yesterday but now I get this error too.
