### ISSUE TITLE
Add warning that hyphens are not supported in database credentials

### ISSUE THREAD

**Issue by GoudronViande24** [vilhelmprytz/pterodactyl-installer#266]
**Describe the bug**
When trying to install pterodactyl panel on Ubuntu 20.04:
`ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-panel' at line 1`

**To Reproduce**
Steps to reproduce the behaviour:
 - Run installation script
 - Enter all the infos
 - The error will happen and the script exits right after

**Expected behaviour**
Pterodactyl panel get installed

**OS (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation: panel only

**More logs**
```bash
Package sebastian/resource-operations is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover || true
Discovered Package: fideloper/proxy
Discovered Package: laracasts/utilities
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: prologue/alerts
Discovered Package: spatie/laravel-fractal
Discovered Package: spatie/laravel-query-builder
Package manifest generated successfully.
57 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Application key set successfully.
* Downloaded pterodactyl panel files & installed composer dependencies!
* Performing MySQL queries..
* Creating MySQL user..
* Creating database..
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-panel' at line 1
```

**Comment by vilhelmprytz** [comment]
What database name and database user name did you use?

**Comment by GoudronViande24** [comment]
pterodactyl-panel for both

**Comment by vilhelmprytz** [comment]
> pterodactyl-panel for both

I see. Because of the way we invoke the SQL queries, hyphens probably won't work. Try wiping your machine and using the default values or something like `pterodactyl_panel` instead.

**Comment by GoudronViande24** [comment]
Yep, I did and it worked. It still should be fixed though, or add a warning to prevent users to do it.

**Comment by vilhelmprytz** [comment]
Yes, I agree. I will keep this issue upon and we'll check if we can add a warning/allow the usage of hyphens. Thanks!
