### ISSUE TITLE
Creating a Database Host Function

### ISSUE THREAD

**Issue by Ferks-FK** [vilhelmprytz/pterodactyl-installer#267]
# [ Explanation ]
I would like to suggest an edit to the wings installation script.

Recently it was implemented the option for you to create the user for the database host creation automatically.

### [ How it currently works ]
An option appears to choose whether or not you want a database host user.
If they choose "Yes", they will be prompted for a user and password, and that is it.

### [ How it could work ]
Before the "User" and "Password" questions appear, ask the user whether the host will be functional only locally, or externally.

### [ Examples: ]

Would you like to create your database host automatically? "Yes"
Will your host be accessible Locally, or externally? ( Local/External )

If the answer is "Local", do it the original way.
If "External", ask for the host IP.

### [ Why this change? ]

Well, the script will not be limited to always creating hosts locally, and it will have an option for this to work in both cases.

**Comment by vilhelmprytz** [comment]
Thank you for submitting this and sorry for the delay!

When you refer to the local/external database user, are you referring to changing the `127.0.0.1` part of this line?
https://github.com/vilhelmprytz/pterodactyl-installer/blob/06c0bda09fa1fb0fe8f179729236595a3f979bf3/install-wings.sh#L472

**Comment by Ferks-FK** [comment]
> Thank you for submitting this and sorry for the delay!
> 
> When you refer to the local/external database user, are you referring to changing the `127.0.0.1` part of this line?
> 
> https://github.com/vilhelmprytz/pterodactyl-installer/blob/06c0bda09fa1fb0fe8f179729236595a3f979bf3/install-wings.sh#L472

Yes
