### ISSUE TITLE
SSL Error installing panel.

### ISSUE THREAD

**Issue by Roblox-Studio** [vilhelmprytz/pterodactyl-installer#269]
**Describe the bug**
SSL Do not work please help

**Expected behaviour**
When i installing the panel the ssl do not work it failed i have try it many times and it do not work please help.

**OS**
 - OS: Ubuntu
 - Installation: [panel]

**Comment by Roblox-Studio** [comment]
Please Help

**Comment by Linux123123** [comment]
Please provide full logs
```
cat /var/log/pterodactyl-installer.log | nc termbin.com 9999
```

**Comment by vilhelmprytz** [comment]
I would recommend joining our [Discord server](https://pterodactyl-installer.se/discord) for help with this. Closing for now.
