### ISSUE TITLE
Potential problem with panel installation script on Debian stretch

### ISSUE THREAD

**Issue by FuryCraft** [vilhelmprytz/pterodactyl-installer#273]
Hello I have this error:
E: Essential packages were removed and -y was used without --allow-remove-essential.
It is after the initial configuration for installing the latest release of Ptero

**Comment by FuryCraft** [comment]
`* Initial configuration completed. Continue with installation? (y/N): y
* Starting installation.. this might take a while!

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch-backports InRelease
Hit:5 http://deb.debian.org/debian stretch Release
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
ufw is already the newest version (0.35-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

* Enabling Uncomplicated Firewall (UFW)
* Opening port 22 (SSH), 80 (HTTP) and 443 (HTTPS)
Firewall is active and enabled on system startup
Firewall reloaded
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 22/tcp                     ALLOW IN    Anywhere
[ 2] 80/tcp                     ALLOW IN    Anywhere
[ 3] 443/tcp                    ALLOW IN    Anywhere
[ 4] 8080                       ALLOW IN    Anywhere
[ 5] 2022                       ALLOW IN    Anywhere

* Installing dependencies for Debian 10..

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
dirmngr is already the newest version (2.1.18-8~deb9u4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version (20200601~deb10u1).
ca-certificates set to manually installed.
lsb-release is already the newest version (10.2019051400).
lsb-release set to manually installed.
The following packages were automatically installed and are no longer required:
  dictionaries-common emacsen-common iamerican ibritish ienglish-common
  iso-codes ispell python-apt-common python3-apt python3-certifi
  python3-chardet python3-debconf python3-debian python3-debianbts
  python3-httplib2 python3-idna python3-pkg-resources python3-pycurl
  python3-pysimplesoap python3-requests python3-six python3-urllib3
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  apt apt-listchanges apt-utils python3-reportbug reportbug task-english
  task-ssh-server tasksel tasksel-data
The following NEW packages will be installed:
  apt-transport-https
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  apt
E0 upgraded, 1 newly installed, 9 to remove and 0 not upgraded.
: Essential packages were removed and -y was used without --allow-remove-essential.
`

**Comment by FuryCraft** [comment]
Thanks, it is working now

**Comment by vilhelmprytz** [comment]
Closing this, for now, reopen if the problem occurs again.
