### ISSUE TITLE
Nginx web server says is active and when i go on the website it fails to load

### ISSUE THREAD

**Issue by Roblox-Studio** [vilhelmprytz/pterodactyl-installer#274]
**Describe the bug**
Nginx web server says is active and when i go on the website it fails to load.
**Expected behaviour**
Nginx web server says is active and when i go on the website it fails to load.

**Screenshots**
![Here](https://user-images.githubusercontent.com/70972052/145708478-211676a0-1a69-4806-927b-b09ff37a6c0b.png)

**OS (please complete the following information):**
 - OS: Ubuntu
 - Installation: panel

**Comment by Roblox-Studio** [comment]
I found how to fix this. You need to use command 

$ sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT
$ sudo netfilter-persistent save

**Comment by Linux123123** [comment]
So that is in no way associated with the script. You are probably running on Oracle cloud.

**Comment by vilhelmprytz** [comment]
As mentioned by @Linux123123, this doesn't seem to be related to the script. Refer to the [Discord server](https://pterodactyl-installer.se/discord) for support with the script. Closing.
