### ISSUE TITLE
Can't continued install wings

### ISSUE THREAD

**Issue by kyrtion** [vilhelmprytz/pterodactyl-installer#276]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to send input `* Initial configuration completed. Continue with installation? (y/N): y`
2. Wait and see error:
`Err:3 http://ppa.launchpad.net/ondrej/php/ubuntu jammy Release
  404  Not Found [IP: 91.189.95.85 80]`
`E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu jammy Release' does not have a Release file.`

**OS (please complete the following information):**
 - OS: Debian 10
 - Installation: wings
![Screenshot_1](https://user-images.githubusercontent.com/63658002/146353931-01c78702-90e8-49a8-883b-961cecb95aff.png)

**Comment by Linux123123** [comment]
Not a clean system.

**Comment by vilhelmprytz** [comment]
As mentioned by @Linux123123, it seems like you did not run the script on a clean installation of Debian. Closing this for now, refer to the [Pterodactyl Installer Discord server](https://pterodactyl-installer.se/discord) for support with the script. Closing.
