### ISSUE TITLE
Get error when connect to SFTP

### ISSUE THREAD

**Issue by MulqiGaming64** [vilhelmprytz/pterodactyl-installer#279]
Error Message: Algorithm Negotiation fail

OS: Ubuntu 18.04

**Comment by Linux123123** [comment]
Not related with the script. Go to [Pterodactyl Discord server](https://pterodactyl-installer.se/discord) for general support.

**Comment by vilhelmprytz** [comment]
As mentioned by @Linux123123, this is most likely not related to the script. Reopen if this is not the case.
