### ISSUE TITLE
Rocky Linux

### ISSUE THREAD

**Issue by Coolgam3r2152** [vilhelmprytz/pterodactyl-installer#283]
It would be nice to have rocky. linux support added since its basically centos 8. Would it be possible to do this?

**Comment by Linux123123** [comment]
Yes, this is already planned. We are just waiting for CentOS 8 to become EOL (tomorrow). Then we will probably replace CentOS 8 support with Rocky linux and AlmaLinux.

**Comment by Linux123123** [comment]
One more thing. Because they are basically the same, I have tested that changing the OS name we check it will work fine without changing anything else with installation.

**Comment by Coolgam3r2152** [comment]
how would I go around changing all the os names myself?

**Comment by Linux123123** [comment]
Download the `install-panel.sh` and then run this in the same directory
```
sed -i -e "s@centos@rocky@g" install-panel.sh
```
Then run the script
```
bash install-panel.sh
```
**Note. It might not work perfectly. I haven't done more extensive testing then** **running in vm and seeing if it fails. Also it might still say CentOS in some** **places.**
