### ISSUE TITLE
bash: /dev/fd/63: No such file or directory

### ISSUE THREAD

**Issue by SkyAcademy** [VilhelmPrytz/pterodactyl-installer#29]
I want to enter the install script, but I get this error:

> shost@scorpius-vds1:~$ sudo bash <(curl -s https://raw.githubusercontent.com/VilhelmPrytz/pterodactyl-installer/master/install-panel.sh)
> **bash: /dev/fd/63: No such file or directory**

**Comment by VilhelmPrytz** [comment]
This issue has already been opened, see #1

You have to make sure you're logged in as root before you run the command.

```bash
sudo -i
```

Then run the command (as root).

```bash
bash <(curl -s https://raw.githubusercontent.com/VilhelmPrytz/pterodactyl-installer/master/install-panel.sh)
```

**Comment by Shwing123** [comment]
The solution doesn't work on my device. I got "**command not found**"  when validating the installation in the following step. 
> 
> 
> This issue has already been opened, see #1
> 
> You have to make sure you're logged in as root before you run the command.
> 
> ```shell
> sudo -i
> ```
> 
> Then run the command (as root).
> 
> ```shell
> bash <(curl -s https://raw.githubusercontent.com/VilhelmPrytz/pterodactyl-installer/master/install-panel.sh)
> ```

**Comment by Linux123123** [comment]
Then try
```
wget https://pterodactyl-installer.se/i.sh
bash i.sh
```

**Comment by FuriousGeinbits** [comment]
For any Linux noobs like me with the same issue in the future, making sure that curl is installed fixed this issue for me.

apt install curl
