### ISSUE TITLE
Database unable to connect

### ISSUE THREAD

**Issue by RecalsZ** [vilhelmprytz/pterodactyl-installer#292]
**Describe the bug**
I am able to create a database for the server but when the server it self is using mysql addon to try to connect to it such as litebans on minecraft it isnt able to connect and i get the error
![image](https://user-images.githubusercontent.com/94567250/148419040-cff25f41-8903-4354-add2-79beba626162.png)
This also happens on my fivem server using mysql resource when i get again, This happens on everything trying to connect
![image](https://user-images.githubusercontent.com/94567250/148419198-bb8d7654-c104-4fb3-8e54-7a5b39599fe8.png)

![image](https://user-images.githubusercontent.com/94567250/148419679-dc9d5d43-2407-4280-9840-97ded842c5f3.png)

**Expected behaviour**
It should normally be able to connect to the database easy, i can do it in phpmyadmin fine but when doing it here i get a issue and the plugins/addons cant connect

**OS (please complete the following information):**
 - OS: Ubuntu
 - Installation: panel and wings

**Comment by vilhelmprytz** [comment]
Did you use the "database host" feature for Wings?

**Comment by RecalsZ** [comment]
I belive i did

**Comment by vilhelmprytz** [comment]
Can you run this command and include the response here?

```bash
grep bind-address /etc/mysql/mariadb.conf.d/50-server.cnf
```

**Comment by RecalsZ** [comment]
bind-address            = 0.0.0.0
the bind address is in red

**Comment by RecalsZ** [comment]
![image](https://user-images.githubusercontent.com/94567250/148451556-46ce7be7-e033-45e6-a61b-471962c8da9e.png)

**Comment by vilhelmprytz** [comment]
Interesting. I assume you are running both panel, wings, and the "database host" on the same machine, correct?

If you also used the automatic firewall option (it uses ufw) you have to allow incoming traffic to 3306 (in case you are trying to access the machine from another host).

**Comment by RecalsZ** [comment]
They are both on the same dedicated machine, i also doubled check to see that ufw did allow it and it did.

**Comment by vilhelmprytz** [comment]
I don't think this is related to the script, so I will close this for now. Please reopen the issue if you are able to reproduce it on the latest canary version of the script (#277 changes how this feature is implemented, although the changes should not affect the problem you are experiencing here).
