### ISSUE TITLE
Can't open Panel Site

### ISSUE THREAD

**Issue by PandaMC66** [vilhelmprytz/pterodactyl-installer#296]
**Describe the bug**
I can't open the Panel :( It says: "Page cannot open because Safari could not connect to the Server"

**OS (please complete the following information):**
 - OS: Ubuntu 20.4
 - Installation: panel & wings

**Comment by Linux123123** [comment]
Provide the script log
```
cat /var/log/pterodactyl-installer.log | nc termbin.com 9999
```

**Comment by PandaMC66** [comment]
https://termbin.com/sh0d

**Comment by Linux123123** [comment]
Letsencypt failed in the panel part and you chose to assume SSL so now you need to create your own certificates and point nginx to them.

**Comment by PandaMC66** [comment]
Sorry im not an Expert 😅 How i made this? xD
