### ISSUE TITLE
Almalinux installer support

### ISSUE THREAD

**Issue by BlueFire2003** [vilhelmprytz/pterodactyl-installer#297]
Is your feature request related to a problem? Yes, the actual script is saying that almalinux8 is not a compatible os but in pterodactyl there is a way to install it(same as centos8 and Rocky Linux8) 

Describe the solution you'd like
To make the script almalinux compatible or create a separate one for it

Why would i need it when there is others os to use? 
Recenly i ran into a problem with a vps where in ubuntu and debian it doesn't connect to its repositoryes websites and commands doesnt work, but for any reason in almalinux work

**Comment by Linux123123** [comment]
Duplicate of #283

**Comment by vilhelmprytz** [comment]
Closing because of duplicate.
