### ISSUE TITLE
Cant configure node

### ISSUE THREAD

**Issue by Senior-S** [vilhelmprytz/pterodactyl-installer#306]
**Describe the bug**
Hi, Im not sure if this are a bug or not but I cant configure my new node

**To Reproduce**
Steps to reproduce the behaviour:
1. Install pterodactyl panel.
2. Go to Nodes, create a new one and name the FQDN to same as the website domain.
3. Run Auto-Deploy command.
4. See error.

**Expected behaviour**
Configure the node and can create servers based in that node.

**Screenshots**
I dont have but I attach the log:
```
map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer KhvYp7vD9Aiya2o1DNr8tOMaFEeN6bbnxMBzwc2rrDFpG9ag] Content-Type:[application/json]]https://*mydomain*/api/application/nodes/1/configurationFailed to fetch configuration from the panel.
 Get "https://*mydomain*/api/application/nodes/1/configuration": x509: certificate is not valid for any names, but wanted to match *mydomain*
```

**OS (please complete the following information):**
 - OS:Ubuntu Server 18.04
 - Installation: panel

**Comment by vilhelmprytz** [comment]
This is not a problem with the script. Refer to the official Pterodactyl project for help with the panel/wings, our to our [Discord](https://pterodactyl-installer.se/discord) for support with the script.
