### ISSUE TITLE
bash: /dev/fd/63: No such file or directory on install

### ISSUE THREAD

**Issue by MattDarkPro** [vilhelmprytz/pterodactyl-installer#311]
**Describe the bug**
After I ran the `sudo bash <(curl -s https://pterodactyl-installer.se)` I get `bash: /dev/fd/63: No such file or directory`

**To Reproduce**
Install a clean Ubuntu server, perform the bash <(curl -s https://pterodactyl-installer.se) command.

**Expected behaviour**
The default installation starts, as seen on https://www.youtube.com/watch?v=E8UJhyUFoHM

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/40952643/159171548-8906c2a4-ba62-46ac-ad83-ea1429d082c2.png)

**OS (please complete the following information):**
Ubuntu Server LTS, downloaded from https://ubuntu.com/download/server
(version ubuntu-20.04.4)

**Comment by Linux123123** [comment]
Do not use `sudo` in front of script. Run it as a `root` user.

**Comment by MattDarkPro** [comment]
Thanks, I'm an idiot.
