### ISSUE TITLE
PHP fatal error when running install script

### ISSUE THREAD

**Issue by Friedsteak1** [vilhelmprytz/pterodactyl-installer#312]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
Run Script on debian 10 as root.

**Expected behaviour**
pterodactyl to install

**Screenshots**

**OS (please complete the following information):**
 - OS: Debian 10
 - Installation: panel and wings
**Additional context**
`Deprecation Notice: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with Ar                                                                                                                                                                                                    rayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily sup                                                                                                                                                                                                    press the notice in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php:1405
Deprecation Notice: Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with Array                                                                                                                                                                                                    Access::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress                                                                                                                                                                                                     the notice in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php:1416
Deprecation Notice: Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible wi                                                                                                                                                                                                    th ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to                                                                                                                                                                                                     temporarily suppress the notice in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php:                                                                                                                                                                                                    1428
Deprecation Notice: Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with Arr                                                                                                                                                                                                    ayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppr                                                                                                                                                                                                    ess the notice in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php:1441
Deprecation Notice: Return type of PhpOption\Some::getIterator() should either be compatible with IteratorAggregate::getI                                                                                                                                                                                                    terator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /v                                                                                                                                                                                                    ar/www/pterodactyl/vendor/phpoption/phpoption/src/PhpOption/Some.php:152
Deprecation Notice: Return type of PhpOption\None::getIterator() should either be compatible with IteratorAggregate::getI                                                                                                                                                                                                    terator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /v                                                                                                                                                                                                    ar/www/pterodactyl/vendor/phpoption/phpoption/src/PhpOption/None.php:118
> @php artisan package:discover || true
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collectio                                                                                                                                                                                                    n::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTy                                                                                                                                                                                                    peWillChange] attribute should be used to temporarily suppress the notice in /var/www/pterodactyl/vendor/laravel/framewor                                                                                                                                                                                                    k/src/Illuminate/Collections/Collection.php:1443
Stack trace:
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(13): Illuminate\Foundation\Boo                                                                                                                                                                                                    tstrap\HandleExceptions->handleError()
#1 /var/www/pterodactyl/vendor/composer/ClassLoader.php(571): include('...')
#2 /var/www/pterodactyl/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): Composer\Autoload\ClassLoade                                                                                                                                                                                                    r->loadClass()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(130): collect()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(106): Illuminate\Foundatio                                                                                                                                                                                                    n\PackageManifest->build()
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): Illuminate\Foundation                                                                                                                                                                                                    \PackageManifest->getManifest()
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\Foundation                                                                                                                                                                                                    \PackageManifest->config()
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\                                                                                                                                                                                                    Foundation\PackageManifest->aliases()
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Bo                                                                                                                                                                                                    otstrap\RegisterFacades->bootstrap()
#10 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundatio                                                                                                                                                                                                    n\Application->bootstrapWith()
#11 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\Foundatio                                                                                                                                                                                                    n\Console\Kernel->bootstrap()
#12 /var/www/pterodactyl/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#13 {main} in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/Collection.php on line 13
PHP Fatal error:  Uncaught Error: Class "Illuminate\Support\Collection" not found in /var/www/pterodactyl/vendor/laravel/                                                                                                                                                                                                    framework/src/Illuminate/Collections/helpers.php:15
Stack trace:
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Traits/ReflectsClosures.php(24): collect()
#1 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Traits/ReflectsClosures.php(44): Illuminate\Found                                                                                                                                                                                                    ation\Exceptions\ReportableHandler->closureParameterTypes()
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/ReportableHandler.php(62): Illumina                                                                                                                                                                                                    te\Foundation\Exceptions\ReportableHandler->firstClosureParameterType()
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(234): Illuminate\Founda                                                                                                                                                                                                    tion\Exceptions\ReportableHandler->handles()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(88): Illuminate                                                                                                                                                                                                    \Foundation\Exceptions\Handler->report()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(130): Illuminat                                                                                                                                                                                                    e\Foundation\Bootstrap\HandleExceptions->handleException()
#6 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#7 {main}
  thrown in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/helpers.php on line 15
57 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collectio                                                                                                                                                                                                    n::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTy                                                                                                                                                                                                    peWillChange] attribute should be used to temporarily suppress the notice in /var/www/pterodactyl/vendor/laravel/framewor                                                                                                                                                                                                    k/src/Illuminate/Collections/Collection.php:1443
Stack trace:
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(13): Illuminate\Foundation\Boo                                                                                                                                                                                                    tstrap\HandleExceptions->handleError()
#1 /var/www/pterodactyl/vendor/composer/ClassLoader.php(571): include('...')
#2 /var/www/pterodactyl/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): Composer\Autoload\ClassLoade                                                                                                                                                                                                    r->loadClass()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(130): collect()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(106): Illuminate\Foundatio                                                                                                                                                                                                    n\PackageManifest->build()
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): Illuminate\Foundation                                                                                                                                                                                                    \PackageManifest->getManifest()
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\Foundation                                                                                                                                                                                                    \PackageManifest->config()
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\                                                                                                                                                                                                    Foundation\PackageManifest->aliases()
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Bo                                                                                                                                                                                                    otstrap\RegisterFacades->bootstrap()
#10 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundatio                                                                                                                                                                                                    n\Application->bootstrapWith()
#11 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\Foundatio                                                                                                                                                                                                    n\Console\Kernel->bootstrap()
#12 /var/www/pterodactyl/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#13 {main} in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/Collection.php on line 13
PHP Fatal error:  Uncaught Error: Class "Illuminate\Support\Collection" not found in /var/www/pterodactyl/vendor/laravel/                                                                                                                                                                                                    framework/src/Illuminate/Collections/helpers.php:15
Stack trace:
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Traits/ReflectsClosures.php(24): collect()
#1 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Traits/ReflectsClosures.php(44): Illuminate\Found                                                                                                                                                                                                    ation\Exceptions\ReportableHandler->closureParameterTypes()
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/ReportableHandler.php(62): Illumina                                                                                                                                                                                                    te\Foundation\Exceptions\ReportableHandler->firstClosureParameterType()
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(234): Illuminate\Founda                                                                                                                                                                                                    tion\Exceptions\ReportableHandler->handles()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(88): Illuminate                                                                                                                                                                                                    \Foundation\Exceptions\Handler->report()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(130): Illuminat                                                                                                                                                                                                    e\Foundation\Bootstrap\HandleExceptions->handleException()
#6 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#7 {main}
  thrown in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/helpers.php on line 15
`

**Comment by vilhelmprytz** [comment]
This is most likely not related to the script. Please refer to the official Pterodactyl project for help with Pterodactyl and feel free to join [our Discord server](https://pterodactyl-installer.se/discord) for help with the script. Closing.
