### ISSUE TITLE
Change docker version install

### ISSUE THREAD

**Issue by SashaGoncharov19** [vilhelmprytz/pterodactyl-installer#314]
If you will use this script to install wings, it installing new docker version which had troubles with displaying docker container stats.

You can saw that if you will install wings on VDS/VPS, install any server and wrote 'docker stats' command on SSH.

![image](https://user-images.githubusercontent.com/65261114/160034990-c0e7bf5e-462e-4c7d-900a-cf052b23ca23.png)
![image](https://user-images.githubusercontent.com/65261114/160035036-596faf18-4e60-422b-b9ae-ff2c50584403.png)

Bug on Ubuntu 20

**Comment by teszeo** [comment]
Same bug on Centos 8

**Comment by teszeo** [comment]
> 

I dont know if you finally got an answer for this issue but at the moment what i did is `sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=1"` and my problem was solved, you can find more info at `https://docs.docker.com/config/containers/runmetrics/`

**Comment by SashaGoncharov19** [comment]
You can type **sudo docker info | grep "Cgroup Version"** to check your active cgroup version.

Should you experience issues with Docker statistics, there are two ways to fix this. Changing the cgroup version to V2 or downgrading containerd to  1.4.13.

To change your Cgroup version open the file at /etc/default/grub and add **systemd.unified_cgroup_hierarchy=1** to the **CMDLINE_LINUX**, without removing any existing parameters inside. Type =1 to enable cgroup V2 and =0 for V1.

It should look similar to **GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1"**. It might contain other existing parameters, in which case, you should add the new one at the end, e.g "swapaccount=1 systemd.unified_cgroup_hierarchy=1"

After that, run **sudo update-grub** followed by **sudo reboot** to apply it and restart the machine.
