### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by ObsidianMC123** [vilhelmprytz/pterodactyl-installer#317]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/76558667/162200758-52c64d77-9d25-419b-b8ad-a0766b792507.png)

**OS (please complete the following information):**
 - OS: ubuntu
 - Installation: panel and wings

**Additional context**
Help please

**Comment by vilhelmprytz** [comment]
Please provide the installation log and other details. You may refer to [our Discord server](https://pterodactyl-installer.se/discord) for support with the script. Closing for now.
