### ISSUE TITLE
cant install docker in Debian 11

### ISSUE THREAD

**Issue by AamiRobin** [vilhelmprytz/pterodactyl-installer#318]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package docker-ce-cli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Package 'docker-ce-cli' has no installation candidate
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'

os Debian 11

**Comment by AamiRobin** [comment]
INFO: [Apr 11 22:48:33.240] loading configuration from file config_file=/etc/pterodactyl/config.yml
 INFO: [Apr 11 22:48:33.240] configured wings with system timezone timezone=Asia/Singapore
 INFO: [Apr 11 22:48:33.240] checking for pterodactyl system user username={0 0}
 INFO: [Apr 11 22:48:33.241] configured system user successfully gid=998 uid=998 username=pterodactyl
 INFO: [Apr 11 22:48:33.241] fetching list of servers from API
 INFO: [Apr 11 22:48:33.287] processing servers returned by the API total_configs=0
 INFO: [Apr 11 22:48:33.288] finished processing server configurations duration=635.625µs
FATAL: [Apr 11 22:48:33.289] failed to configure docker environment error=Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Stacktrace:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
github.com/pterodactyl/wings/cmd.rootCmdRun
        /home/runner/work/wings/wings/cmd/root.go:139
github.com/spf13/cobra.(*Command).execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/pterodactyl/wings/cmd.Execute
        /home/runner/work/wings/wings/cmd/root.go:69
main.main
        /home/runner/work/wings/wings/wings.go:8
runtime.main
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/proc.go:255
runtime.goexit
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581

**Comment by Linux123123** [comment]
Firs provide script logs
```
cat /var/log/pterodactyl-installer.log | nc termbin.com 9999
```

**Comment by AamiRobin** [comment]
its looks like docker are not installed. 
after I tried to install it manually and it worked but there is no CPU and ram uses report.
![image](https://user-images.githubusercontent.com/22963668/162770487-32d025da-f347-4ebc-b721-f44a5551f9a2.png)
![image](https://user-images.githubusercontent.com/22963668/162770494-117b11b6-fb2a-497f-865f-292119f0235f.png)

**Comment by vilhelmprytz** [comment]
How did you install it manually? The script should have created a file, `/etc/apt/sources.list.d/docker.list`, with the apt repo for Docker. Can you check if this file is present and its contents?

**Comment by AamiRobin** [comment]
I did this https://docs.docker.com/engine/install/debian/
 
and this is what you want me to see.
deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian   buster stable

**Comment by vilhelmprytz** [comment]
> I did this https://docs.docker.com/engine/install/debian/
> 
> and this is what you want me to see. deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable

@AamiRobin `buster` is Debian 10 and not Debian 11. I have recently installed using the script on Debian 11 and I did not encounter any issues, so I will close this issue for now. Feel free to reopen if this still occurs.
