### ISSUE TITLE
 In Model.php line 63:                                                                                                                                                 Data integrity exception encountered while performing database write operation. {"username":["The username must start and end with alpha-     numeric characters and\n                contain only letters, numbers, dashes, underscores, and periods."]}       

### ISSUE THREAD

**Issue by HMVOP** [vilhelmprytz/pterodactyl-installer#320]
In Model.php line 63:
                                                                                                                                             
  Data integrity exception encountered while performing database write operation. {"username":["The username must start and end with alpha-  
  numeric characters and\n                contain only letters, numbers, dashes, underscores, and periods."]}       

please solve this this error is showing while updating rust
![Screenshot from 2022-04-19 12-03-09](https://user-images.githubusercontent.com/87656683/163940980-b478a2dd-738b-47f4-9b61-2c3d2bb5a27e.png)

**Comment by Linux123123** [comment]
Please read the error before opening an issue.
![image](https://user-images.githubusercontent.com/26341983/163941279-f1e5a288-23e1-4d65-a131-9c38deb86c17.png)
It is clearly written that you are using a bad username. It is not related with rust at all.

**Comment by HMVOP** [comment]
means which user name i didn't understood

**Comment by Linux123123** [comment]
Pterodactyl admin user's username. The one that you entered here
![image](https://user-images.githubusercontent.com/26341983/163942091-8aab22c8-9e10-4e5e-a1d7-0321509cbd5d.png)

**Comment by HMVOP** [comment]
can u sugget like which name i can take

**Comment by Linux123123** [comment]
Any name. For example
```
hmvop
```

**Comment by vilhelmprytz** [comment]
Not related to script, closing.
