### ISSUE TITLE
Ubuntu 2204 is not Supported!

### ISSUE THREAD

**Issue by Effendil** [vilhelmprytz/pterodactyl-installer#324]
**Describe the bug**
Can't install the Script on Ubuntu 2204 but the compatibility chart says it is supported, but that's a lie.

**To Reproduce**
Try to install it on Unbuntu 2204

**Expected behaviour**
I Expected that I can simply install it on Ubuntu 2204 because on the Description it says this Version is supported.

**Screenshots**
I don't think that a screenshot can help to understand that problem more.

**OS (please complete the following information):**
Ubuntu 22.04

**Comment by Linux123123** [comment]
It is only supported in development version. Choose canary when installing.(Option 3 or 4 or 5)

**Comment by Effendil** [comment]
Wow that's a fast support.

hmm im not really sure if I want to use such an old version.... and now I must reinstall my whole system because of the false chart that says its supported for installation -.-...

What's the reason to only support it for dev-version?

thx for the fast reply =)

**Comment by vilhelmprytz** [comment]
"canary" here refers to the "canary"/development version of the script, not the latest development release of Pterodactyl. It still installs the latest stable Pterodactyl. Ubuntu 22.04 support has just been added, just not yet "released" in the script.

**Comment by Linux123123** [comment]
Can be closed now.

**Comment by vilhelmprytz** [comment]
This was solved in #323
