### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by AlphaMinedime** [vilhelmprytz/pterodactyl-installer#326]
Safari can't connect to the panel website.

**Comment by Ferks-FK** [comment]
This is not script related.

**Comment by AlphaMinedime** [comment]
Neither can google.

**Comment by AlphaMinedime** [comment]
So nobody can help?

**Comment by Ferks-FK** [comment]
Discord pls.

**Comment by AlphaMinedime** [comment]
what the discord?

**Comment by Ferks-FK** [comment]
> what the discord?

https://github.com/vilhelmprytz/pterodactyl-installer#help-and-support

**Comment by vilhelmprytz** [comment]
Not related to the script, closing. Refer to the [Discord server](https://pterodactyl-installer.se/discord) for support with the script.
