### ISSUE TITLE
Install Docker 20.10.16+ on Wings installer script

### ISSUE THREAD

**Issue by Erisfiregamer1** [vilhelmprytz/pterodactyl-installer#329]
**Is your feature request related to a problem? Please describe.**
Docker 20.10.16+ fixes the cgroup issue that breaks statistics. Installing it would make script usage a bit more streamlined since people don't have to upgrade it or use the cgroup fix.

**Describe the solution you'd like**
Bump the docker installed from the script to 20.10.16+.

**Describe alternatives you've considered**
- Automatic CGroup fix (why)

**Additional context**
See .cgroup on the Pterodactyl discord.

**Comment by Ferks-FK** [comment]
`apt update && apt upgrade` solve this. ¯\_(ツ)_/¯

**Comment by Linux123123** [comment]
We do not install a specific version of docker. It is the newest available version in the repositories that we install, so if the repository that you are installing from has the new version the stats should work.

**Comment by Erisfiregamer1** [comment]
Closed, Linux123123 is right.
