### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by Meesjee** [vilhelmprytz/pterodactyl-installer#330]
Hi,
I have used the script on a unbuntu 20.04 VM on VMware on my windows 10 machine. 
The VM says its completed but when i go the panel it says 502 Bad Gateway.
Can some one help me?
![image](https://user-images.githubusercontent.com/54674086/169261887-dcf4e0e4-7b13-4fac-a96e-32aabf99b82b.png)

**Comment by Linux123123** [comment]
Provide the script log.
```
cat /var/log/pterodactyl-installer.log | nc termbin.com 9999
```

**Comment by Meesjee** [comment]
https://termbin.com/9qtsd

**Comment by Linux123123** [comment]
There are no errors in the script (at quick glance). Make sure you are using the correct IP, there are no firewalls and (or) ports on your router are forwarded correctly. You can also try restarting `nginx` with `systemctl restart nginx`.

**Comment by Meesjee** [comment]
A reboot of the vm fixt the problem :)
