### ISSUE TITLE
Add note/warning that the official Pterodactyl Project Discord is not a support resource when using this script

### ISSUE THREAD

**Issue by gOOvER** [vilhelmprytz/pterodactyl-installer#333]
It's really annoying, to help people, which are using this script. Please add a Note or better a WARNING, that people, which are using this script, will not get any support on official Pterodactyl Discord Server

**Comment by vilhelmprytz** [comment]
Sorry for the delay, I somehow missed this issue completely. Do you suggest adding it to the README or some "warning" in the script itself? I admit we're probably not too clear about where people can get support but we usually refer to the Discord server for this project (i.e. https://pterodactyl-installer.se/discord) and not the official Pterodactyl project.

**Comment by vilhelmprytz** [comment]
I don't think this is necessary. The script does not advise using the official channels for help with the script, only for stuff related to Pterodactyl after installation. I'm open to other opinions.

**Comment by gOOvER** [comment]
> I don't think this is necessary. The script does not advise using the official channels for help with the script, only for stuff related to Pterodactyl after installation. I'm open to other opinions.

But you rUseres. Its really annoying to give support for failed scriptinstalls

**Comment by vilhelmprytz** [comment]
> > I don't think this is necessary. The script does not advise using the official channels for help with the script, only for stuff related to Pterodactyl after installation. I'm open to other opinions.
> 
> But your Users. Its really annoying to give support for failed scriptinstalls. 75% of all installations with the script do have problems after or during install and all want support on Ptero Discord

I have no idea where you got that the script doesn't work 75% of the time, that's not true.  There are multiple references to the Discord server created for this project. The only time I refer people to the official Discord server is when the question does not have to do with the installation.
