### ISSUE TITLE
WEBSITE DOWN

### ISSUE THREAD

**Issue by joaoespanhol** [vilhelmprytz/pterodactyl-installer#334]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. WEBSITE DOWN : https://pterodactyl-installer.se/

**Expected behaviour**

**Screenshots**

**OS (please complete the following information):**
 - OS: [e.g. Ubuntu, Debian, CentOS]
 - Installation: [panel or wings]

**Additional context**

**Comment by Linux123123** [comment]
Yes we already know this. You can check https://status.pterodactyl-installer.se/ and (or) our [discord server](https://pterodactyl-installer.se/discord) for updates.

**Comment by joaoespanhol** [comment]
discord server, no this on
https://pterodactyl-installer.se/discord

**Comment by Linux123123** [comment]
Oh yeah that is broken too. :)
Use this [link](https://discord.gg/2zMdudJ)

**Comment by joaoespanhol** [comment]
> 

ok, thanks,
