### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by Erani0** [vilhelmprytz/pterodactyl-installer#335]
The Website is offline

**Comment by Linux123123** [comment]
Duplicate of #334

**Comment by awdojoaidjwad** [comment]
when will the website be online again?

**Comment by Linux123123** [comment]
In https://status.pterodactyl-installer.se/ there are incident reports with ETR. Also you can run the script by using
```
bash <(curl -s https://raw.githubusercontent.com/vilhelmprytz/pterodactyl-installer/master/install.sh)
```
and choosing canary version of the script.

**Comment by awdojoaidjwad** [comment]
> In https://status.pterodactyl-installer.se/ there are incident reports with ETR. Also you can run the script by using
> 
> ```
> bash <(curl -s https://raw.githubusercontent.com/vilhelmprytz/pterodactyl-installer/master/install.sh)
> ```
> 
> and choosing canary version of the script.

Thx Bro :D

**Comment by vilhelmprytz** [comment]
This has been fixed as of 10:23 (UTC+2) today.
