### ISSUE TITLE
Problem While Installing 

### ISSUE THREAD

**Issue by AdamRoyn** [vilhelmprytz/pterodactyl-installer#336]
![Screenshot_20220620-222044_Termius](https://user-images.githubusercontent.com/58103343/174635760-0e20d871-9260-4e9c-a4bc-def4ae1af40e.png)

**Comment by Linux123123** [comment]
You need to the script run on a **clean system only**.

**Comment by AdamRoyn** [comment]
I'll try in a moment, thank you
