### ISSUE TITLE
Installatioin of panel fails if wget is not installed

### ISSUE THREAD

**Issue by joost00719** [vilhelmprytz/pterodactyl-installer#337]
**Describe the bug**
If wget is not installed the script crashes in command not found.
This is on Debian 11

**To Reproduce**
Steps to reproduce the behaviour:
1. Install a clean install of Debian. I used fai-project to create a custom iso
2. login as root
3. apt-get update && apt-get upgrade -y
4. hostnamectl set-hostname 'whateveryouwant'
5. reboot -h now
6. bash <(curl -s https://pterodactyl-installer.se)
7. Option 0
8. *crash*

**Expected behaviour**
I expect the script to install wget as a dependancy.
After installing wget it worked fine.

**Screenshots**
I forgot to take a screenshot

**OS (please complete the following information):**
 - OS: Debian bullseye (11)
 - Installation: panel

**Additional context**
Easy fix would be to add wget

**Comment by joost00719** [comment]
I tried reproducing it in a clean vm, and I have taken a screenshot of the error:
![image](https://user-images.githubusercontent.com/21021559/174827243-fb682646-35d6-40ce-af9c-7a9945cb59b2.png)
somehow the logging does not include the error: https://termbin.com/28gw but feel free to check it out.

**Comment by Linux123123** [comment]
So I can confirm that this is a bug with the script. Debian deb is the only place where we use `wget` so it can be replaced by `curl` which is required to run the script and should be installed. Thanks for reporting.

**Comment by vilhelmprytz** [comment]
Thanks for reporting this, fix will be included in next release!
