### ISSUE TITLE
Opt out of SSL

### ISSUE THREAD

**Issue by TheRealGramdalf** [vilhelmprytz/pterodactyl-installer#346]
**Is your feature request related to a problem? Please describe.**
When using a reverse proxy, using SSL certs with lets encrypt on the panel installation itself is not required/introduces additional complexity/when in a development environment where you don't want to use a domain name or cert at all

**Describe the solution you'd like**
Add an option to opt out of SSL **before entering your letsencrypt email,** which would install everything without certificates - you can then use your reverse proxy to generate the certs instead.

**Describe alternatives you've considered**

**Additional context**

The reason for this is primarily to reduce confusion, as the option is already there - but the script asks for an email to use with letsencrypt as if it were going to install with SSL either way.

**Comment by Linux123123** [comment]
There is already a way to install without SSL.

**Comment by TheRealGramdalf** [comment]
This is mainly for clarifications sake - it appears as if there isn't an option when first running the script.

**Comment by Linux123123** [comment]
There is. You opt out of let's encrypt and opt out of assume SSL. There is nothing more clear. Just answer `n` to all SSL related questions.

**Comment by Linux123123** [comment]
This functionality is already included in the script, closing.
