### ISSUE TITLE
bind: address already in use

### ISSUE THREAD

**Issue by liamgibbins** [vilhelmprytz/pterodactyl-installer#348]
**Describe the bug**
Installed panel and wings on the same VM, after following the install script I get 
FATAL: [Aug 28 21:33:50.369] failed to configure HTTP server error=listen tcp 0.0.0.0:8080: bind: address already in use
when running wings

I am not running letsencrypt and using http as its not exposed to the net

**To Reproduce**
install panel and wings on the same server.

 Ubuntu 22.04

**Comment by vilhelmprytz** [comment]
This is most likely not a problem with the script. Check if something else is listening on port 8080. Refer to the [Discord server](https://pterodactyl-installer.se/discord) for support with the script. Closing.
