### ISSUE TITLE
The nginix says coudn't start ngnix.serverice

### ISSUE THREAD

**Issue by Shriy1556k** [vilhelmprytz/pterodactyl-installer#349]

**Comment by Higor123123** [comment]
You need install first

**Comment by Shriy1556k** [comment]
what do i need to install

**Comment by Shriy1556k** [comment]
it's already there

**Comment by Linux123123** [comment]
Not sure what you are trying to get here. You haven't provided the script logs or anything with your issue. Couldn't start `nginx` could be a million things. It doesn't even indicate that the script failed.

**Comment by vilhelmprytz** [comment]
This is not an issue with the script.
