### ISSUE TITLE
xRDP connection

### ISSUE THREAD

**Issue by zedboi77** [vilhelmprytz/pterodactyl-installer#350]
**Describe the bug**
for some unknown reason i cannot connect to my vps anymore using xrdp after installing panel+wings, is there a configuration/firewall settings in the script that causing the issue?

**To Reproduce**
Steps to reproduce the behaviour:
1. install panel+wing
2. after succesfully install and running it, rdp connection no longer work

**Expected behaviour**
it should connect normally just like before installing pterodactyl

**Screenshots**

**OS (please complete the following information):**
 - OS: Ubuntu
 - Installation: panel and wings

**Additional context**
aws ec2

**Comment by Linux123123** [comment]
Did you use the firewall option? What port is the service you are talking about running on?

**Comment by zedboi77** [comment]
yes, it was the firewall setting. i just had to add rdp port again because it bypass the aws inbound rules for some reason
