### ISSUE TITLE
Script not running on POP OS (based on Ubuntu)

### ISSUE THREAD

**Issue by CreeperBois** [vilhelmprytz/pterodactyl-installer#351]
**Describe the bug**
When I run the script it says that pop 22.04 is not supported

**To Reproduce**
Steps to reproduce the behaviour:
Just Run The Script

**Expected behaviour**
It should run it as pop is bases like almost fully on Ubuntu
**OS (please complete the following information):**
 - OS: [Pop OS based on Ubuntu]
 - Installation: [panel or wings] - both

**Additional context**
Can u like provide me some information like I can remove the checking of the os or you can add support

**Comment by Linux123123** [comment]
Pop OS is indeed not supported. Ubuntu based doesn't mean, that it will have the same package versions and be supported the same. Please use normal Ubuntu or any other supported OS.

Also, as a sidenote, you should be running software like this on a server OS's, not desktop.

**Comment by CreeperBois** [comment]
means that desktop version is not supported?

**Comment by Linux123123** [comment]
It is supported if you run vanilla Ubuntu desktop

**Comment by CreeperBois** [comment]
ok
