### ISSUE TITLE
Script broken since new Panel release v1.10.4?

### ISSUE THREAD

**Issue by flumpi** [vilhelmprytz/pterodactyl-installer#352]
**Describe the bug**
When I run the script any option just gets stuck.

**To Reproduce**
Steps to reproduce the behaviour:
1. run the script
2. pick any option

**Expected behaviour**
Install.

**OS (please complete the following information):**
 - OS: Ubuntu
 - Installation: panel or wings

**Comment by Linux123123** [comment]
The script didn't change as it always pulls the latest version. Please check if you have a stable internet connection.

**Comment by Linux123123** [comment]
The script currently does work and there are no issues with it getting stuck. Please reopen if the issue persists.
