### ISSUE TITLE
/dev/fd/63 does not exist, even running as root

### ISSUE THREAD

**Issue by DarkWolfe5** [vilhelmprytz/pterodactyl-installer#355]
**Describe the bug**
Following all the youtubes and reading through old issues here and still getting the following error when trying to run "bash <(curl https://petrodactyl-installer.se)"
     bash: /dev/fd/63: No such file or directory
I've tried running as root, using "sudo su" "sudo -i" as normal user, and unlocking and logging in directly as root, with and without "sudo" to varied results, none of which actually run the script

**To Reproduce**
1. Fresh install of Ubuntu 20.04
2. Let OS fully update
3. Login as normal user
4. open terminal
5. run "sudo apt update && sudo apt upgrade -y"
6. apt fully updated/upgraded
7. set password for root "sudo passwd root"
8. unlock root user "sudo passwd -u root"
9. Reboot
10. Login as root
11. open terminal
12. run command "bash <(curl -s https://petrodactyl-installer.se)"
13. see nothing happens
14. run command "sudo bash <(curl -s https://petrodactyl-installer.se)"
15. get error: "bash: /dev/fd/63: No such file or directory"
16. Logout
17. login as normal user
18. open terminal
19. run "sudo -i" to open root user prompt
20. repeat steps 10 - 13
21. run "sudo su" (still as root user prompt)
22. repeat step 10-11
23. Be confused why this worked earlier before reinstalling OS from scratch but cancelled script mid-run for...reasons -_-

**Expected behavior**
I expected to see the script run.

**Screenshots**
(Can't seem to upload screenshot. It keeps failing)

**OS (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation: Attempting to install 

**Additional context**

**Comment by Linux123123** [comment]
Try running this as root:
```bash
wget https://pterodactyl-installer.se/i.sh
bash i.sh
```

**Comment by DarkWolfe5** [comment]
> Try running this as root:
> 
> ```shell
> wget https://pterodactyl-installer.se/i.sh
> bash i.sh
> ```

wget gave me the following:
--2022-11-19 11:12:57--  https://petrodactyl-installer.se/i.sh
Resolving petrodactyl-installer.se (petrodactyl-installer.se)... failed: Name or service not known.
wget:  unable to resolve host address 'petrodactyl-installer.se'

Ran this as root via "sudo -i"

**Comment by DarkWolfe5** [comment]
*facepalm* I've been misspelling pterodactyl this whole time... gotta love dyslexia!
*eyeroll at self*
