### ISSUE TITLE
/dev/fd/62: line 781: ufw: command not found

### ISSUE THREAD

**Issue by AamiRobin** [vilhelmprytz/pterodactyl-installer#357]
**Describe the bug**
(ebtables) in auto mode
Setting up ufw (0.36-7.1) ...

Creating config file /etc/ufw/before.rules with new version

Creating config file /etc/ufw/before6.rules with new version

Creating config file /etc/ufw/after.rules with new version

Creating config file /etc/ufw/after6.rules with new version
Created symlink /etc/systemd/system/multi-user.target.wants/ufw.service → /lib/systemd/system/ufw.service.
Processing triggers for libc-bin (2.31-13+deb11u5) ...
Processing triggers for rsyslog (8.2102.0-2+deb11u1) ...
Processing triggers for man-db (2.9.4-2) ...

* Enabling Uncomplicated Firewall (UFW)
* Opening port 22 (SSH), 80 (HTTP) and 443 (HTTPS)
/dev/fd/62: line 781: ufw: command not found

**To Reproduce**
Steps to reproduce the behaviour:
when installing panel 

**Screenshots**
https://i.imgur.com/tuelGV6.png

**OS (please complete the following information):**
 - OS: Debian fresh install
 - Installation: Panel

**Comment by AamiRobin** [comment]
also i tried with ubuntu 22.04 and it working fine but it installing php 8.0

https://i.imgur.com/etoUo9L.png

**Comment by Linux123123** [comment]
So when canary version is used you get this error and when stable is used you don't?

**Comment by AamiRobin** [comment]
I used 
bash <(curl -s https://pterodactyl-installer.se)
and it works with ubuntu but not Debien. also, it installed PHP 8.0 not 8.1

**Comment by Linux123123** [comment]
Which options did you choose after running the aforementioned command?
PHP 8.1 is only available if using the canary version.

**Comment by AamiRobin** [comment]
i used 0

**Comment by AamiRobin** [comment]
Creating config file /etc/ufw/after6.rules with new version
Created symlink /etc/systemd/system/multi-user.target.wants/ufw.service → /lib/systemd/system/ufw.service.
Processing triggers for libc-bin (2.31-13+deb11u5) ...
Processing triggers for rsyslog (8.2102.0-2+deb11u1) ...
Processing triggers for man-db (2.9.4-2) ...
/tmp/lib.sh: line 366: ufw: command not found

* SUCCESS: Enabled Uncomplicated Firewall (UFW)

* Opening ports: 22 (SSH), 80 (HTTP) and 443 (HTTPS)
/tmp/lib.sh: line 392: ufw: command not found


canary also has same issue with Debian 11

**Comment by Linux123123** [comment]
Are you running the script as `root` and if yes in what way do you access that root account? Like `sudo su` or `sudo -i`

**Comment by AamiRobin** [comment]
in Debian its su to get root access

**Comment by Linux123123** [comment]
It's everywhere `su` to access `root` account. Just sometimes, it doesn't load the `$PATH` correctly. Please try one of my mentioned ways to access `root` and then run the script.

**Comment by AamiRobin** [comment]
https://i.imgur.com/X7gsab2.png

**Comment by Linux123123** [comment]
Either install `sudo` using `apt` or `ssh` to `root` account directly. Also, an option is to not install a `firewall`.
