### ISSUE TITLE
Unable to install panel on CentOS 8

### ISSUE THREAD

**Issue by DemOnJR** [VilhelmPrytz/pterodactyl-installer#40]
**Describe the bug**
The nginx work perfectly until i installed the panel,
After the installer has finished i get that error.

**To Reproduce**
1. Run installer
2. Finish the install
3. See error

**Expected behaviour**
The nginx work perfectly until i installed the panel.

**Screenshots**
https://cdn.discordapp.com/attachments/682356044898500634/682602923683086435/unknown.png

**OS:**
 - OS: Centos 8
 - Installation: Panel

**Additional context**
I get this error only on Centos 8, on ubuntu 18.04 is working corectly.

**Comment by VilhelmPrytz** [comment]
Do you have any additional logs (installation log, nginx error log or PHP fpm error log)?

**Comment by VilhelmPrytz** [comment]
So, I just tried installing CentOS 8 in a VirtualBox machine (and then use the script). It worked without any problems. Can you provide some further logs to help me debug this issue?

PHP-fpm logs:

```bash
cat /var/log/php-fpm/error.log
```

Pterodactyl logs:

```bash
tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log
```

nginx logs

```bash
cat /var/log/nginx/pterodactyl.app-error.log
```

Thanks!

**Comment by DemOnJR** [comment]
i will try, thanks.

**Comment by VilhelmPrytz** [comment]
Closing this in favour of #51 which I think can be related.

@DemOnJR Re-open this issue if I am incorrect!
