### ISSUE TITLE
Let's Encrypt setup is never called on Debian (causing install to fail)

### ISSUE THREAD

**Issue by GermanKingYT** [VilhelmPrytz/pterodactyl-installer#42]
**Describe the bug**
Website dont work after install

**To Reproduce**
Steps to reproduce the behaviour:
install it on debian 10

 - OS:Debian 10
 - Installation:  panel

**Additional context**

lets encrypt have some probs i think
log:
https://minereaper-my.sharepoint.com/:w:/r/personal/marc_minereaper_onmicrosoft_com/_layouts/15/WopiFrame.aspx?sourcedoc=%7B9322162e-edec-454a-9e76-469d532cb5c6%7D&action=default&originalPath=aHR0cHM6Ly9taW5lcmVhcGVyLW15LnNoYXJlcG9pbnQuY29tLzp3Oi9nL3BlcnNvbmFsL21hcmNfbWluZXJlYXBlcl9vbm1pY3Jvc29mdF9jb20vRVM0V0lwUHM3VXBGbm5aR25WTXN0Y1lCZmtCSmd1Nk9SWkRCaHAtNXdmR0o5QT9ydGltZT1ITkQ4WkgzRDEwZw&cid=35a36023-44ee-4b63-aca4-7363e639b26d

**Comment by VilhelmPrytz** [comment]
Thank you for reporting this, I'll solve it right away.
