### ISSUE TITLE
What ports do I need to forward to my server?

### ISSUE THREAD

**Issue by GitMinimal** [VilhelmPrytz/pterodactyl-installer#43]
What ports should I forward from my router to my server? 

Is it just the ones I added to the firewall, or should I add 80, 443, etc..

**Comment by VilhelmPrytz** [comment]
This is outside the scope of the script. If you installed the panel, it would be `80` (HTTP) and `443` (HTTPS). For the daemon, it would be `8080` (if you didn't change it) and `2022` for the SFTP.

**Comment by GitMinimal** [comment]
Hey, I got it worked out.

Although I'm having an issue with my ark server.

It says that it is online but I can't connect/ping it via steam. I have a
minecraft server running just fine and I can connect with no problems.
Any ideas?

Thanks,
Bret Peavy

**Comment by VilhelmPrytz** [comment]
Great you got it running. I am not the creator of the Pterodactyl panel itself, this is merely an installation script for it. I'd recommend you talk to the people over at the official Pterodactyl project Discord server.

If I'd guess of something: make sure you have also opened the port that Ark uses on the daemon.
