### ISSUE TITLE
Firewall is closed during the certbot acme challenge verification

### ISSUE THREAD

**Issue by arantesxyz** [VilhelmPrytz/pterodactyl-installer#44]
**Describe the bug**
The script automatically runs certbot before opening the firewall, if the firewall is closed the acme challenge will fail.

**To Reproduce**
Steps to reproduce the behaviour:
1. Close port 80 on your firewall
2. Run the script
3. You'll see the certbot error

**Expected behaviour**
The firewall script should run before the cerbot.

Btw you should run on the following order:
Open port 80 on firewall -> run certbot -> run nginx
(nginx also fails bcz theres no certificate installed)

**Screenshots**
https://prnt.sc/rin2ps

**OS (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation: panel

**Comment by VilhelmPrytz** [comment]
Oops, I must have missed this issue! That's a good point, I'll see what I can do (I don't have much time at the moment).

**Comment by VilhelmPrytz** [comment]
@arantesxyz I have now implemented a fix for this. Mind trying it out? Reopen the issue if it's still broken!

**Comment by arantesxyz** [comment]
Thank you. I'll try asap
