### ISSUE TITLE
Standalone SFTP Server

### ISSUE THREAD

**Issue by Boy132** [VilhelmPrytz/pterodactyl-installer#45]
Pterodactyl offers to use a standalone sftp server instead of the built-in one.
Maybe add an option to automatically enable or at least install the standalone sftp server?

More official infos here: https://pterodactyl.io/daemon/standalone_sftp.html

**Comment by VilhelmPrytz** [comment]
Thank you for opening an issue! This could definitely be implemented. If anyone would like to try and implement this, I would be happy to accept a pull request. Otherwise, I'll implement it myself once I got the time to do so.

**Comment by VilhelmPrytz** [comment]
This has now been implemented. Give it a go! 😀
