### ISSUE TITLE
Automatic 500

### ISSUE THREAD

**Issue by YoiBoiGal8xy** [VilhelmPrytz/pterodactyl-installer#49]
Ubuntu 18.04
After running both scripts i get a automatic 500 any way i can fix this?

**Comment by VilhelmPrytz** [comment]
This usually occurs when something went wrong during installation. A lot of people just press enter to accept the default values during configuration, but there is one step where it asks if you want to "migrate the database" and the default answer is no. Pressing enter there invalidates the whole installation. I'd suggest you to join the Discord server if you want support (GitHub issues only for bugs/features).
