### ISSUE TITLE
Help! Fresh install (out of memory)

### ISSUE THREAD

**Issue by GooberOTF** [vilhelmprytz/pterodactyl-installer#490]
Just made my first install. Got it working and node working (green heart). Got the command panel showing that steam CMD was pulling down my counterstrike 2 server. It stops mid way and says out of memory. Tells me I don't have any room on my machine. The VM was made with 100 GB virtual hard drive. 

Please help!! I finally got it to work / connect and then I hit this road block! 

Thanks!!

**Comment by Hackpig1974** [comment]
I may know what you got going on. When I create Ubuntu VMs, the installer does a great job of getting the VM up and running, but it doesn't sort the drives all the way out. I think you will find that if you run some commands and check, Ubuntu did not fully utilize the space. 

Command to check: lsblk
You are looking at the volume is labeled "ubuntu--vg-ubuntu--lv"
You will probably find that it is only using a portion of the drive size you requested. If that is the case here is the commands you run.

lvextend -l +100%FREE /dev/ubuntu-vg/ubuntu-lv
resize2fs /dev/ubuntu-vg/ubuntu-lv

Now confirm that it is now taking all the space by running the command again: lsblk 

Not sure of your distro, but I have this baked into my process for when I create new VM's with Ubuntu. Good luck.

**Comment by sinjs** [comment]
An "out of memory" error means that you do not have enough RAM available for the gameserver to function. How much RAM did you allocate to the CS2 Server?
