### ISSUE TITLE
panel: CentOS 8 fails due to wrong path (sudo -i / sudo su)

### ISSUE THREAD

**Issue by Ainillia** [vilhelmprytz/pterodactyl-installer#51]
Hello,

The panel install might fail on some basic/custom CentOS images because of `PATH` environment variables and Nginx not creating conf.d (for some reason).

1st issue is composer not working because it does not get linked into the environment, so I get command not found. It works if, before calling composer, i create the symlink :

```bash
ln -s /usr/local/bin/composer /usr/bin/composer
```

Else you get this:

```bash
/dev/fd/63: ligne 204: composer : commande introuvable
PHP Warning:  require(/var/www/pterodactyl/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/pterodactyl/artisan on line 18
```

This is caused by path not updating (depends how you get into `root`, it works via root login but not with user login then `sudo -i` to transfer env vars)

2nd issue is, for some reason, Nginx does not create conf.d upon install, which leads to the curl line pulling config into pterodactyl.conf to fail because folder does not exists :

```bash
* Configuring nginx ..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /etc/nginx/conf.d/pterodactyl.conf: no file or folder of this type
```

a fix would ensure that conf.d folder exists beforehand.

Thank you.

**Comment by vilhelmprytz** [comment]
Sorry for the delay on this one. This has not been reported by anyone else and I believe CentOS 8 panel on the new version of the script (the one for the beta `pterodactyl-1.0`, #52) is reported to work (I tested it as well). Are you able to test the new version of the script and/or if this is still an issue?

**Comment by Ainillia** [comment]
Hello, 

No problem. I haven't tested the new script/beta but i'll retest later. You can close the issue if you want.
Maybe you could try with elevated root access in secured environnement ("sudo -i" from a sudo user instead of direct root login, some machines or cloud environments do not allow direct root connection or "su -", hence how i found the bug)

**Comment by vilhelmprytz** [comment]
Oh, I haven't tested that specifically! I'll make sure I do.

**Comment by vilhelmprytz** [comment]
I just tested this with `sudo -i` on the canary version of the script. Working all good. I think this issue was resolved somewhere at some point, but I can't recall how. Let me know if this is still a problem for you and reopen the issue. Closing.
