### ISSUE TITLE
Automatic Let's Encrypt configuration for daemon

### ISSUE THREAD

**Issue by Hoerli1337** [vilhelmprytz/pterodactyl-installer#58]
**Is your feature request related to a problem? Please describe.**
The installation script of the daemon does not create an SSL certificate.
There is still a query missing, which domain should be used incl. installing the certbot and issuing a certificate.
If you install everything on one system, it works without problems. If you separate panel and daemon, it will not work.

**Describe alternatives you've considered**
If i install certbot and create my own ssl-certificate all works fine :)

**Comment by vilhelmprytz** [comment]
This is long overdue. Moving to the `pterodactyl-1.0` milestone. Should be included in PR #52 (separate PR to merge to that branch).
