### ISSUE TITLE
redis and redis-server packages fail to install

### ISSUE THREAD

**Issue by FoksVHox** [vilhelmprytz/pterodactyl-installer#59]
**Describe the bug**
When I use the script I get this:
> Errors ere encountered while processing:
>  redis-server
>  redis
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**To Reproduce**
1. Go to execute the bash command in 
2. Use NGINX
3. Use the default Database name
4. Use the default Database user name
5. Use a domain
6. Don't use UFW
7. Use Lets Encrypt
8. Wait until you see this
![image](https://user-images.githubusercontent.com/37844753/82580288-40528580-9b8f-11ea-888f-0ec4ea8377bc.png)
9. Wait until the database has to be migrated
10. Errors

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/37844753/82580288-40528580-9b8f-11ea-888f-0ec4ea8377bc.png)

**OS:**
 - OS: Ubuntu 18.04
 - Installation: 0.1.17

**Comment by vilhelmprytz** [comment]
Thank you for reporting this. Can you scroll up a bit in the terminal and see if there is any more information regarding why the errors occurred?

**Comment by FoksVHox** [comment]
I don't see any other errors before that one.

**Comment by vilhelmprytz** [comment]
@FoksVHox Look closely, when `dpkg` says it encountered errors it means that the actual errors occurred earlier so therefore the error messages should be higher up.

**Comment by FoksVHox** [comment]
The only thing that I see is this, however, I don't think it is the thing: 
![image](https://user-images.githubusercontent.com/37844753/82582163-ed2e0200-9b91-11ea-8e9f-bb3dd0b1b0bd.png)

Also, is there a specific pattern that the other errors should look like?

**Comment by vilhelmprytz** [comment]
@FoksVHox There is no specific pattern. Is it possible for you to copy the whole log (all the way back from where the script was started) and attach it on GitHub Gist or something like hastebin?

**Comment by FoksVHox** [comment]
I'll try

**Comment by FoksVHox** [comment]
[log.txt](https://github.com/vilhelmprytz/pterodactyl-installer/files/4663659/log.txt)

**Comment by vilhelmprytz** [comment]
@FoksVHox Hmm, that is very strange. Can you check with `systemctl status redis-server` what went wrong?

**Comment by FoksVHox** [comment]
This, and I've no idea what it is / why it is happing
![image](https://user-images.githubusercontent.com/37844753/82584605-05535080-9b95-11ea-9a70-b3d9e03f84ba.png)

**Comment by vilhelmprytz** [comment]
I just tried the script myself and had no issues with this. You can check for Redis errors in `/var/log/redis/redis-server.log`. From the log you sent earlier, I saw that you are not using the default mirrors for Ubuntu (`archive.ubuntu.com`) and instead some `contabo.net` mirror. I'd recommend checking with them. Use the Discord server for support. Closing since this is not an issue with the script.

**Comment by FoksVHox** [comment]
I checked with them and it wasn't an issue with them.

I found that using `apt install -y redis-server` causes that issue, the fix for it is using `apt-get install -y redis-server`

**Comment by vilhelmprytz** [comment]
> @vilhelmprytz 
> I checked with them and it wasn't an issue with them.
> 
> I found that using `apt install -y redis-server` causes that issue, the fix for it is using `apt-get install -y redis-server`
> 

That is very strange. Can you find any information on why this is the case?

**Comment by FoksVHox** [comment]
I can try, but it got rid of the error, but it still has some issues with starting the redis-server and migrating the database.

**Comment by vilhelmprytz** [comment]
> I can try, but it got rid of the error, but it still has some issues with starting the redis-server and migrating the database.

Alright. Use the Discord server for support. If you find any information suggesting that there is an issue with the script itself, feel free to reopen the issue.
