### ISSUE TITLE
The installer wont install

### ISSUE THREAD

**Issue by marrobHD** [VilhelmPrytz/pterodactyl-installer#6]
Here are the logs. Sorry for german: https://pastie.io/ozujtj.x86asm

**Comment by VilhelmPrytz** [comment]
Sorry for late reply. First off, it seems like you've left the database information empty as well as the FQDN. Then it seems like your php installation isn't working properly, as the installer isn't able to perform php commands. Make sure you have a clean OS installation before using the script.

**Comment by marrobHD** [comment]
There isnt a check for the insereted data

**Comment by VilhelmPrytz** [comment]
No, there isn't. I believe the MySQL values do have a default value that will be set if left empty, but the FQDN is required.
