### ISSUE TITLE
Doesnt work with Debian 10 stable update

### ISSUE THREAD

**Issue by NadirBK** [vilhelmprytz/pterodactyl-installer#60]
![image](https://user-images.githubusercontent.com/19260941/82595033-3dfb2600-9ba5-11ea-92b6-3ec744317cbf.png)

**Comment by vilhelmprytz** [comment]
You are using some weird version of Debian sid and not Debian 10.

**Comment by vilhelmprytz** [comment]
I will be closing this for now since clean installs of Debian 10 are detected by the script. Reopen the issue if this is not the case. Use Discord server for general support.
