### ISSUE TITLE
Script stops when certbot cannon issue a certificate.

### ISSUE THREAD

**Issue by arantesxyz** [vilhelmprytz/pterodactyl-installer#61]
**Describe the bug**
When installing the panel, almost at the end of the script, if for some reason certbot fails to create the ssl the script just exit.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the script
2. Make certbot fails the cert
3. See error.

**Expected behaviour**
If certbot fails, the script should ask if the user still wants to continue the installation with ssl enabled or if he want it to fall back to http.

(I would love the option to continue assuming ssl, because for me certbot will always fail - not a bug, that's my server configuration)

**OS (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation: panel

**Comment by vilhelmprytz** [comment]
This is for the Pterodactyl 1.0 version of the script, correct? (#52)

**Comment by arantesxyz** [comment]
> This is for the Pterodactyl 1.0 version of the script, correct? (#52)

Correct!

**Comment by vilhelmprytz** [comment]
Will be closed when #52 merges. Thank you @Linux1231233 for the contribution!
