### ISSUE TITLE
wings: Add link to configuration guide (official documentation)

### ISSUE THREAD

**Issue by Sam1370** [vilhelmprytz/pterodactyl-installer#63]
At the end of the installation, you have to look around online for the steps in order to configure the daemon. I think it would be much easier if, at the end of the script, we added these lines (perhaps tweaking a little for coherence):

```
The guide to configuring your daemon can be found here: https://pterodactyl.io/daemon/0.6/installing.html#configure-daemon
Please run 'systemctl start wings' after the configuration.
```

**Comment by vilhelmprytz** [comment]
Will be closed when #52 merges.
