### ISSUE TITLE
panel: Insert theme selector

### ISSUE THREAD

**Issue by Sam1370** [vilhelmprytz/pterodactyl-installer#64]
TheFonix has some pretty good themes for the Pterodactyl panel available on [his GitHub repository](https://github.com/TheFonix/Pterodactyl-Themes). Below is a function that prompts the user which theme they want to install (if any), and performs the installation. It would be convenient for this function to be called somewhere in the installation script, eliminating the need for the themes to be installed separately from the panel.

```
pick_themes() {
	echo "Here, you can choose to install one of TheFonix's Pterodactyl themes."
	echo "Access previews and read more here: https://github.com/TheFonix/Pterodactyl-Themes"
	echo "These themes are not affiliated in any way with this installation script. Use at your own risk."
	echo "[0] Do not install any themes"
	echo "[1] Pink and Fluffy"
	echo "[2] Tango Twist"
	echo "[3] Blue Brick"
	echo "[4] Minecraft Madness"
	echo "[5] Lime Stitch"
	echo "[6] Red Ape"
	echo "[7] Black and the End of Space"
	echo "[8] Nothing but Graphite"
	cd /var/www/pterodactyl/
	while :
	do
		printf "Choose your theme: "
		read option
		case $option in
			0 ) echo "Keeping the vanilla Pterodactyl theme"
				break
				;;
			1 ) echo "Installing Pink and Fluffy"
				curl https://raw.githubusercontent.com/TheFonix/Pterodactyl-Themes/master/MasterThemes/PinkAnFluffy/build.sh | sh
				echo "Installed theme."
				break
				;;
			2 ) echo "Installing Tango Twist"
				invalid=false
				curl https://raw.githubusercontent.com/TheFonix/Pterodactyl-Themes/master/MasterThemes/TangoTwist/build.sh | sh
				echo "Installed theme."
				break
				;;
			3 ) echo "Installing Blue Brick"
				invalid=false
				curl https://raw.githubusercontent.com/TheFonix/Pterodactyl-Themes/master/MasterThemes/BlueBrick/build.sh | sh
				echo "Installed theme."
				break
				;;
			4 ) echo "Installing Minecraft Madness"
				invalid=false
				curl https://raw.githubusercontent.com/TheFonix/Pterodactyl-Themes/master/MasterThemes/MinecraftMadness/build.sh | sh
				echo "Installed theme."
				break
				;;
			5 ) echo "Installing Lime Stitch"
				invalid=false
				curl https://raw.githubusercontent.com/TheFonix/Pterodactyl-Themes/master/MasterThemes/LimeStitch/build.sh | sh
				echo "Installed theme."
				break
				;;
			6 ) echo "Installing Red Ape"
				invalid=false
				curl https://raw.githubusercontent.com/TheFonix/Pterodactyl-Themes/master/MasterThemes/RedApe/build.sh | sh
				echo "Installed theme."
				break
				;;
			7 ) echo "Installing Black and the End of Space"
				invalid=false
				curl https://raw.githubusercontent.com/TheFonix/Pterodactyl-Themes/master/MasterThemes/BlackEndSpace/build.sh | sh
				echo "Installed theme."
				break
				;;
			8 ) echo "Installing Nothing But Graphite"
				invalid=false
				curl https://raw.githubusercontent.com/TheFonix/Pterodactyl-Themes/master/MasterThemes/NothingButGraphite/build.sh | sh
				echo "Installed theme."
				break
				;;
			* ) echo "Invalid selection"
				;;
		esac
	done
}
```

**Comment by Linux1231233** [comment]
@Sam1370 You could make a pull request with changes that you want to make. Also as of right now themes are kinda broken for the beta versions. Also choosing a theme without a preview for people that haven't seen these themes would be kinda hard. But I agree that adding this would be a great idea. 🙂

**Comment by Sam1370** [comment]
@Linux1231233 Yes, I considered making a pull request, but I have no idea where in the code I should put this, haha. 

Themes are broken in the beta versions, but that doesn't eliminate their usefulness in the others. :)

Choosing a theme without a preview is hard, which is why I provided the link to his repository in the code, you can click and see previews. I am going to edit the code so that it explicitly says "for previews click here" or similar.

**Comment by vilhelmprytz** [comment]
While I can understand the ease-of-use of a theme chooser I am generally opposed to Pterodactyl themes in general. Pterodactyl is yet to provide a solid theme management system (as far as I know, correct me if I'm wrong) which means that most themes online simply override existing Pterodactyl files. This is generally considered bad practice and could be potentially hazardous since a "theme" could inject malicious code. Just theming and styling is unlikely to be harmful.

**Comment by Linux1231233** [comment]
We could add a link to themes repository at the end of the panel installation.

**Comment by Sam1370** [comment]
> which means that most themes online simply override existing Pterodactyl files.

A zipped backup is created of the original files in the directory.

**Comment by Sam1370** [comment]
@Linux1231233 Yes, that is a good idea. I will add one to my initial post.

**Comment by vilhelmprytz** [comment]
@Sam1370 Even if a zipped backup is created, injecting malicious code is still possible. Now, I don't doubt the themes we're talking about are safe to use but I still am a little wary of using third-party themes at this stage. :slightly_smiling_face:

**Comment by Sam1370** [comment]
@vilhelmprytz I see.

**Comment by vilhelmprytz** [comment]
I'll close this for now, but when Pterodactyl provides a more natural way of installing and choosing themes, I'll be more than happy to reopen the issue. As it is now, I would like to see any contributions towards rewriting the "installation completed" message. Perhaps a link to the themes you have been referring to as well as a link to the documentation (#63)? I'd happily accept a PR with this! :slightly_smiling_face:

**Comment by Sam1370** [comment]
@vilhelmprytz Well, if we’re going to provide a link to the themes anyway, why not give an easy way for them to be installed? We could make it clear that these themes are not affiliated with the installation script and that it will directly overwrite Pterodactyl files. You said you did not doubt the safety of the themes, so they should be fine as long as we warn the user sufficiently about what is going to happen to their panel :)

**Comment by vilhelmprytz** [comment]
@Sam1370 Sorry for the confusion; I am not familiar with the themes in question but since I was talking about the security hazard I just wanted to point out the fact that I am not saying that the theme repo in question is malicious, just that third-party themes have the risk of being malicious. Hope I'm making sense :slightly_smiling_face:

**Comment by Sam1370** [comment]
@vilhelmprytz That's true, so we can only include themes that are open-source and have not received any complaints of being malicious, like the example given here. :)

**Comment by vilhelmprytz** [comment]
> @vilhelmprytz That's true, so we can only include themes that are open-source and have not received any complaints of being malicious, like the example given here. :)

Alright, I understand your point. As mentioned I am opposed to the usage of themes and quite frankly the installation of these themes are fairly easy as it is. Don't you think a list of recommended next steps or add-ons is easy enough for most people? In that way, the add-ons are not endorsed nor discouraged.

**Comment by Sam1370** [comment]
@vilhelmprytz That is true, it is fairly easy. I agree with your suggestion.

**Comment by vilhelmprytz** [comment]
Reopened this as I have now customized the "goodbye" message for the panel. Let me know if you have any other suggestions for the goodbye message.
