### ISSUE TITLE
panel: Add option to enable mobile app support

### ISSUE THREAD

**Issue by Sam1370** [vilhelmprytz/pterodactyl-installer#69]
There is a mobile app for Pterodactyl, available on iOS and Android. However, for it to work, a few commands need to be run from the panel directory:
```
composer config repositories.cloud composer https://packages.pterodactyl.cloud

composer require pterodactyl/mobile-addon --update-no-dev --optimize-autoloader

php artisan migrate
```
(taken from https://pterodactyl.cloud/home).
This is the official app -- no third-party software, so I think it would be nice to have a prompt during the installation that asked users if they would like to add support for the mobile app.

**Comment by vilhelmprytz** [comment]
I reckon this can be added for the Pterodactyl 1.0 PR (branch). Should be fairly straightforward to implement!

**Comment by vilhelmprytz** [comment]
Correct me if I am wrong, but I think the Pterodactyl app doesn't work with 1.0? (sorry for the delay)

**Comment by Sam1370** [comment]
Not sure, but that would make sense

**Comment by Linux123123** [comment]
In pterodactyl discord there is this 
![image](https://user-images.githubusercontent.com/26341983/104201119-11e12d80-5432-11eb-94a6-0e5f0d07dfe2.png)
and this
![image](https://user-images.githubusercontent.com/26341983/104201193-26bdc100-5432-11eb-8c8a-c14b334aa94b.png)

**Comment by vilhelmprytz** [comment]
The only app I can see is https://play.google.com/store/apps/details?id=io.pterodactyl.app Do you know if it still works?

**Comment by Linux123123** [comment]
> The only app I can see is https://play.google.com/store/apps/details?id=io.pterodactyl.app. Do you know if it still works?

On 0.7 with a module I think it works.

**Comment by vilhelmprytz** [comment]
Closing since the app is not yet supported on 1.0 (sorry for the delay). Reopen once that happens and we will add it!
