### ISSUE TITLE
Add a troubleshooting script

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#74]
**Is your feature request related to a problem? Please describe.**
I got bored writing the same commands to people over and over again.

**Describe the solution you'd like**
Create a script which automatically runs all the commands needed for troubleshooting, then give it to us (or even use pastebinit to give only the link) .

**Describe alternatives you've considered**
Not applicable.

**Additional context**
Not applicable.

**Comment by vilhelmprytz** [comment]
This is a very good idea! I'll be sure to work on this as soon as I have the time too! In the meanwhile, I thought I could leave a couple of commands here that are good for debugging.

#### Panel

```bash
tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log
```
Retrieve the last 100 lines from the Laravel log.

```bash
/usr/bin/php /var/www/pterodactyl/artisan queue:work --queue=high,standard,low --sleep=3 --tries=3
```
This is periodically run using cron and will show up if the user has misconfigured their session management (Redis) or email (which is usually an okay error).

#### Daemon (not new Wings)

```bash
systemctl stop wings && cd /srv/daemon && npm start
```

Just starting the daemon can actually give quite a lot of information. Stopping the `systemd` service makes sure there are not two instances of the daemon running simultaneously.

Let me know if I missed anything here.

**Comment by Linux123123** [comment]
The [bird-bot](https://github.com/pterodactyl-installer/bird-bot) will have a troubleshooting script which will send back all the information to us, so this isn't necessarily needed.
