### ISSUE TITLE
Adding the .env template and automatically filling it in.

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#75]
**Is your feature request related to a problem? Please describe.**
Lots of people don't know what to select in the `php artisan p:environment:setup`, `php artisan p:environment:database`, `php artisan p:environment:mail` commands.

**Describe the solution you'd like**
Creating a .env file template, and replacing the crucial variables in it.

**Describe alternatives you've considered**
Not applicable.

**Comment by vilhelmprytz** [comment]
Good idea! Perhaps Jinja2 or similar could be used to easily fill in variables? (templating)
