### ISSUE TITLE
Add option to auto-generate passwords and remember them through the installer

### ISSUE THREAD

**Issue by YeapGuy** [vilhelmprytz/pterodactyl-installer#78]
There should be an option to automatically generate the Panel DB password. I always go to a passwords generator and put it in anyway.
The installer should also remember the password you input during the first interactive config and input it automatically later in the installation when it asks for it (this should also be the case for manually inputted passwords)

**Comment by Linux1231233** [comment]
@YeapGuy As of right now the parts where you choose redis, passwords, smtp , etc. is not possible to autofill. We are working on the solution ( issue #75 ). Generating password automatically would not be a great idea, because it would be hard to troubleshoot and remember.

**Comment by YeapGuy** [comment]
Fair enough. I'll close this then.

**Comment by vilhelmprytz** [comment]
While I agree with @Linux1231233, perhaps the option to auto-generate the MySQL password would be feasible? Troubleshooting is still possible since you can login with `mysql -u pterodactyl` as Unix `root` without providing a password.

**Comment by YeapGuy** [comment]
Well, that's what I meant by "panel DB password".

**Comment by vilhelmprytz** [comment]
Alright. I'll reopen this, but as @Linux1231233 mentioned, changes from #75 are planned so this issue should be put to be implemented after #75.

**Comment by vilhelmprytz** [comment]
@YeapGuy Thanks again for suggesting this. The feature has now been implemented in the canary version of the script. It will go live for the next release. You can try the changes by using options 6 or 8.
