### ISSUE TITLE
Errors processing redis-server, redis.

### ISSUE THREAD

**Issue by RamonRobben** [vilhelmprytz/pterodactyl-installer#79]
**Describe the bug**
```
Errors were encountered while processing:
 redis-server
 redis
E: Sub-process /usr/bin/dpkg returned an error code (1)

dpkg: error processing package redis-server (--configure):
 installed redis-server package post-installation script subprocess returned error exit status 1

dpkg: dependency problems prevent configuration of redis:
 redis depends on redis-server (<< 5:4.0.9-1ubuntu0.2.1~); however:
  Package redis-server is not configured yet.
 redis depends on redis-server (>= 5:4.0.9-1ubuntu0.2); however:
  Package redis-server is not configured yet.

dpkg: error processing package redis (--configure):
 dependency problems - leaving unconfigured
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a fresh install of Ubuntu 18.04 (64 Bit)
2. Run the script using the suggested command
3. After it gets to redis it will crash

**Expected behaviour**
I expected it to just install and configure redis.

**Screenshots**

**OS (please complete the following information):**
 - OS: Ubuntu 18.04 (64 Bit)
 - Installation: [panel or daemon] panel

**Additional context**
Nope.

**Comment by RamonRobben** [comment]
In the redis log I found this:
17639:C 30 Jul 21:45:55.684 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
17639:C 30 Jul 21:45:55.684 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=17639, just started
17639:C 30 Jul 21:45:55.684 # Configuration loaded
17640:M 30 Jul 21:45:55.686 # Creating Server TCP listening socket ::1:6379: bind: Cannot assign requested address

So I assume the issue comes from IPv6 being disabled on my specific VPS. On some VPS's it might be enabled by default.
I'll re-install my VPS then enable IPv6 and then run the script again to see if that fixes the issue.

**Comment by Linux1231233** [comment]
This isn't strictly the scripts fault. There are problems with dpkg in your vps.

**Comment by vilhelmprytz** [comment]
Thank you for reporting this issue. I believe this is not related to the script, but something else. What hosting provider is this? I've heard that some people have had issues with `redis` using certain providers.

I'll be closing this issue for now, but you are welcome to join the Discord server if you want support for the script! ([https://discord.gg/2zMdudJ](https://discord.gg/2zMdudJ)) If it turns out that this is indeed a bug with the script, don't hesitate to reopen the issue! :slightly_smiling_face:
