### ISSUE TITLE
Minor typos in script and in README

### ISSUE THREAD

**Issue by EramsorGR** [VilhelmPrytz/pterodactyl-installer#8]
**Describe the bug**
When finishing the SSL question (assume SSL or not), 
"Inital configuration done. Do you wan't to continue with the installation?"
Issues: "Inital" should Initial and "wan't" want
also here on github, "steps to reproduce the behavior", behaviour.
 
**To Reproduce**
1. Start the panel script
2. Complete the steps and finish the SSL assumption.

**Expected behavior**
Nothing changed. Just spelling.

**Screenshots**
![image](https://user-images.githubusercontent.com/32240230/64321480-4a186680-cfc9-11e9-8478-c7080118a06a.png)

**OS (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation: panel

**Additional context**
I recommend the use of Grammarly to fix typos and stuff :) It's free and cool.

**Comment by VilhelmPrytz** [comment]
Thank you for your issue report. I realize that there are plenty of typos in this script, thanks for mentioning. I also use Grammarly, but that's not available outside of the browser 😄 .

I'll fix the issues ASAP. However, feel free to send a Pull Request with the proposed changes.

**Comment by VilhelmPrytz** [comment]
Typos are now fixed.
