### ISSUE TITLE
Automatically skipping question if panel/database has been installed while installing Wings

### ISSUE THREAD

**Issue by RamonRobben** [vilhelmprytz/pterodactyl-installer#81]
**Is your feature request related to a problem? Please describe.**
Some people just don't read text above a question clearly.

**Describe the solution you'd like**
Automatically skip the question if a MySQL instance is detected on the system.

**Describe alternatives you've considered**
None.

**Additional context**
Small addition to the script. After you have installed only the panel and want to install the Wings using the same script. It tells you that if you have the panel installed you should answer no to the next question. But can't this just be skipped since you can just check if a panel has been installed and then skip that option for the user by default?

Referring to when it asks if you want to install MariaDB in the Wings script.

**Comment by vilhelmprytz** [comment]
Sorry for the delay, will see if this can be implemented now :slightly_smiling_face:

**Comment by vilhelmprytz** [comment]
It only took me 9 months and 19 days to implement this! :slightly_smiling_face:

**Comment by RamonRobben** [comment]
> It only took me 9 months and 19 days to implement this! 🙂

Hahaha np this issue probably got lost somewhere :P
