### ISSUE TITLE
Arch Linux/Manjaro Support?

### ISSUE THREAD

**Issue by creepinson** [vilhelmprytz/pterodactyl-installer#82]
Can you please add Arch Linux/Manjaro support? I couldn't get it to work with docker or docker-compose so i wanted to use this but it only supports ubuntu and other distros :/
I got this upon running it:
`bash: /proc/self/fd/11: No such file or directory`

Edit: i found this: https://aur.archlinux.org/packages/pterodactyl-panel/
Not sure if it will work

**Comment by Linux1231233** [comment]
So adding support for arch is a lot of work and then a lot of work maintaining it. The AUR package is pretty good tho so you should use it instead. I don't think we will ever support it. We are trying to support the list of OS's that are in [https://pterodactyl.io/panel/0.7/getting_started.html#picking-a-server-os](url)

**Comment by vilhelmprytz** [comment]
> Can you please add Arch Linux/Manjaro support? I couldn't get it to work with docker or docker-compose so i wanted to use this but it only supports ubuntu and other distros :/
> I got this upon running it:
> `bash: /proc/self/fd/11: No such file or directory`
> 
> Edit: i found this: https://aur.archlinux.org/packages/pterodactyl-panel/
> Not sure if it will work

@creepinson As @Linux1231233 mentioned, this script will not support Arch Linux/Manjaro. Those are desktop distributions, I don't know why you would want Pterodactyl to run there in the first place. 🙂 

Regarding the issue you are having running the script, is this running it on Ubuntu? The script is tested to work on Ubuntu. I'd recommend joining the [Discord server](https://discord.gg/2zMdudJ) for help.

You can always try downloading and then running the script.
```baah
wget https://raw.githubusercontent.com/vilhelmprytz/pterodactyl-installer/master/install.sh
bash install.sh
```
Closing.
