### ISSUE TITLE
Use Let's Encrypt --nginx over standalone webserver

### ISSUE THREAD

**Issue by vilhelmprytz** [vilhelmprytz/pterodactyl-installer#88]
**Is your feature request related to a problem? Please describe.**
The standalone webserver option could cause problems later on for renewals, since then nginx is running and occupying the HTTP/HTTPS ports.

**Describe the solution you'd like**
Since certbot does support nginx it would be better to use `certbot --nginx`.

**Describe alternatives you've considered**
None.

**Additional context**
Mentioned in the Discord server.

**Comment by vilhelmprytz** [comment]
Waiting for #91 to be merged before working on this.

**Comment by Linux123123** [comment]
Is the title correct here? Isn't the option `--nginx`. I think there is no such option `--certbot`. Of course correct me if I am wrong.

**Comment by vilhelmprytz** [comment]
> Is the title correct here? Isn't the option `--nginx`. I think there is no such option `--certbot`. Of course correct me if I am wrong.

Fixed.

**Comment by Linux123123** [comment]
Also this should be assigned to me :+1:

**Comment by vilhelmprytz** [comment]
> Also this should be assigned to me 
> 
> (because basically I have already done this)

Fixed. I have yet had the time to review your PRs.
