### ISSUE TITLE
panel: debian_based_letsencrypt function not found (pterodactyl-1.0)

### ISSUE THREAD

**Issue by yourboyjoe** [vilhelmprytz/pterodactyl-installer#89]
`/dev/fd/62: line 811: debian_based_letsencrypt: command not found`
i installed certbot

**Comment by vilhelmprytz** [comment]
> `/dev/fd/62: line 811: debian_based_letsencrypt: command not found`
> i installed certbot

@yourboyjoe Is this the beta version of the script?

**Comment by vilhelmprytz** [comment]
@yourboyjoe I just pushed a commit that I believe fixes this, can you try if it works OK?

**Comment by yourboyjoe** [comment]
Ok.

**Comment by yourboyjoe** [comment]
Thanks it works now!
