### ISSUE TITLE
wings/panel: Option to update to latest versions

### ISSUE THREAD

**Issue by LucidAPs** [vilhelmprytz/pterodactyl-installer#94]
I think it would be really beneficial for the community to have an option on the master script that will update the panel and wings to the latest versions, so an update option.

**Comment by vilhelmprytz** [comment]
Thank you for the suggestion. A separate script doing this would definitely be feasible! Though, perhaps for versions after 1.0 and not prior?

**Comment by Linux123123** [comment]
I agree. We have a lot of stuff in beta branch add/updated. We totally need to wait for 1.0 so we can merge everything into master.

**Comment by LucidAPs** [comment]
The final version is out, i hope you can include the update/upgrade option now.

**Comment by vilhelmprytz** [comment]
> The final version is out, i hope you can include the update/upgrade option now.

If [these are the only steps](https://pterodactyl.io/panel/1.0/upgrade/0.7_to_1.0.html) required to upgrade panel from 0.7 to 1.0, I should be able to do this quite easily. [The Wings migration](https://pterodactyl.io/wings/1.0/migrating.html) shouldn't be too difficult either. I'll see what I can do.

**Comment by LucidAPs** [comment]
An update option for going from 1.0 betas to the latest final 1.0 would be great aswell and possibly even easier to do. Thank you for taking the time :)

**Comment by vilhelmprytz** [comment]
Sorry for the massive delay on this issue, I've just completely forgotten about this issue. I think we've missed the chance to have an upgrade script ready for 0.7.x to 1.x.x. Is there still an interest in this type of script? Or for upgrading from 1.x.x to newer 1.x.x versions?

**Comment by LucidAPs** [comment]
Upgrading from 1.x.x to newer 1.x.x would be a great feature! No point to do 0.7.x to 1.x.x since its no longer supported.

**Comment by vilhelmprytz** [comment]
I see, yes. The upgrade path is usually the same but perhaps we could do something. I currently don't have the time to implement this but I'll leave this open!

**Comment by Linux123123** [comment]
So recently the pterodactyl team rolled out an `artisan` tool to automate upgrading. 
![image](https://user-images.githubusercontent.com/26341983/118387256-35a5c180-b626-11eb-8750-88243a53c219.png)
I think that it still has some problems as I have heard their are sometimes problems when upgrading with it, but it should be the go to way to upgrade the panel.

**Comment by vilhelmprytz** [comment]
The perhaps we don't need an upgrade script? One command isn't really complicated to run manually 🙂

**Comment by Linux123123** [comment]
Yes I also think that if it is just `cd /var/www/pterodactyl` and then `php artisan p:upgrade` it is easy enough to do it yourself.

**Comment by LucidAPs** [comment]
Thats good news for people above 1.3.2 but I am on 1.2.2 and the upgrade process is not easy at all. Also I wonder if the upgrade script also handles wings or just the panel.

**Comment by Linux123123** [comment]
So writing a script to upgrade from <1.3.2 is a niche case. The upgrade process isn't complicated at all if you read the documentation provided. It only gets harder if you need to upgrade dependencies, like upgrading PHP. And the process of upgrading wings is even easier. The only thing that I can think upgrade scripts would be useful is to upgrade dependencies and then run that easy to use upgrade command. The same could be done with wings.

**Comment by LucidAPs** [comment]
Thank you for considering it, yes the dependencies are definitely the harder part for upgrading. If there is no upgrade option through your guys installation script my only option (and I assume for many others) would be to format everything and run the latest version of your script again.

**Comment by vilhelmprytz** [comment]
I think we can definitely implement a upgrade script for Wings. It should be fairly easy to implement and I can see why it makes it easier. As for panel, I am not too sure if it's worth bothering for the older v1.x.x versions? What do you have think?

**Comment by kubo6472** [comment]
> 
> 
> I think we can definitely implement a upgrade script for Wings. It should be fairly easy to implement and I can see why it makes it easier. As for panel, I am not too sure if it's worth bothering for the older v1.x.x versions? What do you have think?

I think if someone is willing enough to make a working PR for Panel 1.0.x-1.2.x -> 1.3.x then it will be included. If not, then do not mind. I also think that it is probably time to drop pre-1.0 from the installer. Last time I ran it, it was still there.

**Comment by vilhelmprytz** [comment]
It's been some time since this was opened. Do we still need an update script? The process of updating is quite straightforward as it is nowadays.

**Comment by Linux123123** [comment]
I believe it's not necessary as in some time the self updater will work again and so the script would be useless.
