### ISSUE TITLE
Remove pterodactyl

### ISSUE THREAD

**Issue by Minemobs** [vilhelmprytz/pterodactyl-installer#95]
Hello, i want to remove pterodactyl and reinstall it with docker.
How do i unistall it ?

**Comment by vilhelmprytz** [comment]
This script is not related to the official project.

**Comment by Minemobs** [comment]
I know, I've install pterodacyl with this script and i wanted to know if i can remove it.

**Comment by vilhelmprytz** [comment]
> I know, I've install pterodacyl with this script and i wanted to know if i can remove it.

This is not an issue with the script. I'd recommend you to ask for help in the official Pterodactyl Discord server.

**Comment by Minemobs** [comment]
Ok thanks
