### ISSUE TITLE
can't connect the daemon to the panel

### ISSUE THREAD

**Issue by alexjub94** [vilhelmprytz/pterodactyl-installer#97]
Hello, 

I've just installed pterodactyl with your script. I selected panel and daemon at the begining and when i set the configuration in ```core.json``` and then ```npm start``` it doesn't work. 

Please don't close this ticket to send me on th discord, they didn't solve the problem.

Thanks by advance.

<img width="514" alt="Capture" src="https://user-images.githubusercontent.com/35138272/94071500-4a61ea80-fdf4-11ea-807f-1e8cec8797e8.PNG">

**Comment by vilhelmprytz** [comment]
Sorry, but this is not an issue with the script. With the information you have provided I can find nothing wrong. The daemon is listening to the port. Are the correct ports opened in the firewall? (`8080` and `2022`). Make sure you [followed the instructions](https://github.com/vilhelmprytz/pterodactyl-installer#daemon). Closing. Refer to the Discord for support with the script.
